// Expanded data - 20+ per major section
const VOCAB = [
{id:1,nl:"de woning",en:"the house",example:"Ik zoek een woning.",cat:"housing"},
{id:2,nl:"de huur",en:"the rent",example:"De huur is hoog.",cat:"housing"},
{id:3,nl:"de verhuurder",en:"the landlord",example:"Ik bel de verhuurder.",cat:"housing"},
{id:4,nl:"het contract",en:"the contract",example:"Ik teken het contract.",cat:"housing"},
{id:5,nl:"de buren",en:"the neighbours",example:"Mijn buren zijn aardig.",cat:"housing"},
{id:6,nl:"het afval",en:"the waste",example:"Ik scheid het afval.",cat:"housing"},
{id:7,nl:"GFT",en:"organic waste",example:"GFT in de groene bak.",cat:"housing"},
{id:8,nl:"de huisarts",en:"the GP",example:"Ik ga naar de huisarts.",cat:"health"},
{id:9,nl:"de apotheek",en:"the pharmacy",example:"Medicijnen bij de apotheek.",cat:"health"},
{id:10,nl:"de afspraak",en:"the appointment",example:"Ik heb een afspraak.",cat:"daily"},
{id:11,nl:"ziek",en:"ill",example:"Ik ben ziek.",cat:"health"},
{id:12,nl:"het recept",en:"the prescription",example:"Ik heb een recept.",cat:"health"},
{id:13,nl:"de zorgverzekering",en:"health insurance",example:"Iedereen heeft zorgverzekering.",cat:"health"},
{id:14,nl:"het eigen risico",en:"the deductible",example:"Eigen risico is 385 euro.",cat:"health"},
{id:15,nl:"werken",en:"to work",example:"Ik werk fulltime.",cat:"work"},
{id:16,nl:"de baan",en:"the job",example:"Ik zoek een baan.",cat:"work"},
{id:17,nl:"het salaris",en:"the salary",example:"Mijn salaris is netto.",cat:"work"},
{id:18,nl:"de werkgever",en:"the employer",example:"Mijn werkgever is goed.",cat:"work"},
{id:19,nl:"de werknemer",en:"the employee",example:"Ik ben werknemer.",cat:"work"},
{id:20,nl:"het CV",en:"the résumé",example:"Ik stuur mijn CV.",cat:"work"},
{id:21,nl:"solliciteren",en:"to apply",example:"Ik ga solliciteren.",cat:"work"},
{id:22,nl:"het gesprek",en:"the interview",example:"Ik heb een gesprek.",cat:"work"},
{id:23,nl:"de uitkering",en:"the benefit",example:"Ik krijg een uitkering.",cat:"work"},
{id:24,nl:"de toeslag",en:"the allowance",example:"Ik vraag toeslag aan.",cat:"work"},
{id:25,nl:"DigiD",en:"digital ID",example:"Ik log in met DigiD.",cat:"government"},
{id:26,nl:"de gemeente",en:"the municipality",example:"Ik ga naar de gemeente.",cat:"government"},
{id:27,nl:"het paspoort",en:"the passport",example:"Mijn paspoort is verlopen.",cat:"government"},
{id:28,nl:"de identiteitskaart",en:"the ID card",example:"Ik heb een ID-kaart.",cat:"government"},
{id:29,nl:"stemmen",en:"to vote",example:"Ik mag stemmen.",cat:"government"},
{id:30,nl:"de koning",en:"the king",example:"Willem-Alexander is de koning.",cat:"government"},
{id:31,nl:"de Tweede Kamer",en:"House of Representatives",example:"De Tweede Kamer maakt wetten.",cat:"government"},
{id:32,nl:"de premier",en:"the prime minister",example:"De premier leidt de regering.",cat:"government"},
{id:33,nl:"het onderwijs",en:"education",example:"Onderwijs is belangrijk.",cat:"education"},
{id:34,nl:"de school",en:"the school",example:"Mijn kind gaat naar school.",cat:"education"},
{id:35,nl:"VMBO",en:"pre-vocational",example:"Hij doet VMBO.",cat:"education"},
{id:36,nl:"HAVO",en:"higher general",example:"HAVO is voor HBO.",cat:"education"},
{id:37,nl:"VWO",en:"pre-university",example:"VWO is voor universiteit.",cat:"education"},
{id:38,nl:"de universiteit",en:"the university",example:"Hij studeert aan de universiteit.",cat:"education"},
{id:39,nl:"het diploma",en:"the diploma",example:"Ik heb mijn diploma.",cat:"education"},
{id:40,nl:"de bibliotheek",en:"the library",example:"Ik ga naar de bibliotheek.",cat:"daily"},
{id:41,nl:"de supermarkt",en:"the supermarket",example:"Ik doe boodschappen.",cat:"daily"},
{id:42,nl:"de rekening",en:"the bill",example:"Ik betaal de rekening.",cat:"daily"},
{id:43,nl:"betalen",en:"to pay",example:"Ik betaal met pin.",cat:"daily"},
{id:44,nl:"de pinpas",en:"the debit card",example:"Ik heb een pinpas.",cat:"daily"},
{id:45,nl:"afspraak maken",en:"to make appointment",example:"Ik maak een afspraak.",cat:"daily"},
{id:46,nl:"op tijd",en:"on time",example:"Kom op tijd.",cat:"daily"},
{id:47,nl:"te laat",en:"late",example:"Ik ben te laat.",cat:"daily"},
{id:48,nl:"de bus",en:"the bus",example:"Ik ga met de bus.",cat:"daily"},
{id:49,nl:"de trein",en:"the train",example:"De trein vertrekt.",cat:"daily"},
{id:50,nl:"het station",en:"the station",example:"Ik wacht op het station.",cat:"daily"},
{id:51,nl:"de fiets",en:"the bicycle",example:"Ik ga met de fiets.",cat:"daily"},
{id:52,nl:"het verkeer",en:"the traffic",example:"Er is veel verkeer.",cat:"daily"},
{id:53,nl:"het weer",en:"the weather",example:"Het weer is slecht.",cat:"daily"},
{id:54,nl:"regenen",en:"to rain",example:"Het regent.",cat:"daily"},
{id:55,nl:"de vakantie",en:"the holiday",example:"Ik ga op vakantie.",cat:"daily"},
{id:56,nl:"vrij",en:"free",example:"Morgen ben ik vrij.",cat:"daily"},
{id:57,nl:"het feest",en:"the party",example:"We vieren een feest.",cat:"daily"},
{id:58,nl:"Koningsdag",en:"King's Day",example:"Op Koningsdag is alles oranje.",cat:"government"},
{id:59,nl:"Sinterklaas",en:"Saint Nicholas",example:"Sinterklaas komt in december.",cat:"government"},
{id:60,nl:"de 4e mei",en:"Remembrance Day",example:"Op 4 mei herdenken we.",cat:"government"},
{id:61,nl:"de 5e mei",en:"Liberation Day",example:"Op 5 mei is Bevrijdingsdag.",cat:"government"},
{id:62,nl:"gelijkheid",en:"equality",example:"Iedereen is gelijk.",cat:"government"},
{id:63,nl:"discrimineren",en:"to discriminate",example:"Discrimineren is verboden.",cat:"government"},
{id:64,nl:"de wet",en:"the law",example:"Je moet de wet volgen.",cat:"government"},
{id:65,nl:"het recht",en:"the right",example:"Iedereen heeft rechten.",cat:"government"},
{id:66,nl:"de vrijheid",en:"the freedom",example:"Er is vrijheid van meningsuiting.",cat:"government"},
{id:67,nl:"de mening",en:"the opinion",example:"Iedereen mag een mening hebben.",cat:"government"},
{id:68,nl:"helpen",en:"to help",example:"Kun je me helpen?",cat:"daily"},
{id:69,nl:"begrijpen",en:"to understand",example:"Ik begrijp het niet.",cat:"daily"},
{id:70,nl:"uitleggen",en:"to explain",example:"Kun je het uitleggen?",cat:"daily"},
{id:71,nl:"de brief",en:"the letter",example:"Ik schrijf een brief.",cat:"daily"},
{id:72,nl:"het formulier",en:"the form",example:"Ik vul het formulier in.",cat:"daily"},
{id:73,nl:"aanvragen",en:"to apply for",example:"Ik vraag toeslag aan.",cat:"government"},
{id:74,nl:"ontvangen",en:"to receive",example:"Ik heb een brief ontvangen.",cat:"daily"},
{id:75,nl:"sturen",en:"to send",example:"Ik stuur een e-mail.",cat:"daily"},
{id:76,nl:"de e-mail",en:"the email",example:"Ik stuur een e-mail.",cat:"work"},
{id:77,nl:"het netwerk",en:"the network",example:"Een netwerk is belangrijk.",cat:"work"},
{id:78,nl:"ervaring",en:"experience",example:"Ik heb ervaring.",cat:"work"},
{id:79,nl:"de vaardigheid",en:"the skill",example:"Communicatie is een vaardigheid.",cat:"work"},
{id:80,nl:"sollicitatiebrief",en:"application letter",example:"Ik schrijf een sollicitatiebrief.",cat:"work"},
{id:81,nl:"de klacht",en:"the complaint",example:"Ik heb een klacht.",cat:"daily"},
{id:82,nl:"repareren",en:"to repair",example:"Kunt u repareren?",cat:"housing"},
{id:83,nl:"lekken",en:"to leak",example:"De kraan lekt.",cat:"housing"},
{id:84,nl:"de verwarming",en:"the heating",example:"De verwarming doet het niet.",cat:"housing"},
{id:85,nl:"het ziekenhuis",en:"the hospital",example:"Hij ligt in het ziekenhuis.",cat:"health"},
{id:86,nl:"de specialist",en:"the specialist",example:"Ik ga naar een specialist.",cat:"health"},
{id:87,nl:"de verloskundige",en:"the midwife",example:"Ik ga naar de verloskundige.",cat:"health"},
{id:88,nl:"de WW",en:"unemployment benefit",example:"Ik krijg WW.",cat:"work"},
{id:89,nl:"de Belastingdienst",en:"Tax Office",example:"Ik regel toeslagen bij de Belastingdienst.",cat:"government"},
{id:90,nl:"de UWV",en:"Employee Insurance",example:"Bij werkloosheid naar UWV.",cat:"work"},
{id:91,nl:"opstaan",en:"to get up",example:"Ik sta om 7 uur op.",cat:"daily"},
{id:92,nl:"aankomen",en:"to arrive",example:"De trein komt aan.",cat:"daily"},
{id:93,nl:"meenemen",en:"to take along",example:"Neem je jas mee.",cat:"daily"},
{id:94,nl:"opruimen",en:"to tidy up",example:"Ik ruim op.",cat:"daily"},
{id:95,nl:"kunnen",en:"can",example:"Ik kan Nederlands.",cat:"daily"},
{id:96,nl:"moeten",en:"must",example:"Je moet op tijd komen.",cat:"daily"},
{id:97,nl:"willen",en:"to want",example:"Ik wil werken.",cat:"daily"},
{id:98,nl:"mogen",en:"may",example:"Mag ik hier parkeren?",cat:"daily"},
{id:99,nl:"uitnodigen",en:"to invite",example:"Ik nodig je uit.",cat:"daily"},
{id:100,nl:"de boete",en:"the fine",example:"Je krijgt een boete.",cat:"housing"},
{id:101,nl:"doorverwijzen",en:"to refer",example:"De huisarts verwijst door.",cat:"health"},
{id:102,nl:"het vast contract",en:"permanent contract",example:"Ik heb een vast contract.",cat:"work"},
{id:103,nl:"het tijdelijk contract",en:"temporary contract",example:"Ik heb een tijdelijk contract.",cat:"work"},
{id:104,nl:"de polder",en:"polder",example:"Nederland heeft polders.",cat:"government"},
{id:105,nl:"de Grondwet",en:"the Constitution",example:"Artikel 1 van de Grondwet.",cat:"government"},
{id:106,nl:"de leerplicht",en:"compulsory education",example:"Er is leerplicht.",cat:"education"},
{id:107,nl:"de basisschool",en:"primary school",example:"Kinderen gaan naar de basisschool.",cat:"education"},
{id:108,nl:"vriendelijk",en:"friendly",example:"Wees vriendelijk.",cat:"work"},
{id:109,nl:"flexibel",en:"flexible",example:"Ik ben flexibel.",cat:"work"},
{id:110,nl:"betrouwbaar",en:"reliable",example:"Ik ben betrouwbaar.",cat:"work"},
{id:111,nl:"de sfeer",en:"the atmosphere",example:"Goede werksfeer.",cat:"work"},
{id:112,nl:"de ontwikkeling",en:"the development",example:"Ik wil me ontwikkelen.",cat:"work"},
{id:113,nl:"de kraan",en:"the tap",example:"De kraan lekt.",cat:"housing"},
{id:114,nl:"de schutting",en:"the fence",example:"Er is ruzie over de schutting.",cat:"housing"},
{id:115,nl:"de wachtlijst",en:"the waiting list",example:"Er is een wachtlijst.",cat:"housing"},
{id:116,nl:"sociale huur",en:"social housing",example:"Ik zoek sociale huur.",cat:"housing"},
{id:117,nl:"de huisartsenpost",en:"out-of-hours GP",example:"Ik ga naar de huisartsenpost.",cat:"health"},
{id:118,nl:"de CAO",en:"collective agreement",example:"Salaris volgens CAO.",cat:"work"},
{id:119,nl:"open sollicitatie",en:"open application",example:"Ik stuur een open sollicitatie.",cat:"work"},
{id:120,nl:"de uitslag",en:"the result",example:"De uitslag is goed.",cat:"health"},
{id:121,nl:"de keuken",en:"the kitchen",example:"De keuken is schoon.",cat:"housing"},
{id:122,nl:"de badkamer",en:"the bathroom",example:"De badkamer is bezet.",cat:"housing"},
{id:123,nl:"de slaapkamer",en:"the bedroom",example:"Ik slaap in de slaapkamer.",cat:"housing"},
{id:124,nl:"de woonkamer",en:"the living room",example:"We zitten in de woonkamer.",cat:"housing"},
{id:125,nl:"het raam",en:"the window",example:"Doe het raam open.",cat:"housing"},
{id:126,nl:"de deur",en:"the door",example:"Doe de deur dicht.",cat:"housing"},
{id:127,nl:"de sleutel",en:"the key",example:"Ik zoek mijn sleutel.",cat:"housing"},
{id:128,nl:"de lift",en:"the elevator",example:"Neem de lift.",cat:"housing"},
{id:129,nl:"de trap",en:"the stairs",example:"Ga de trap op.",cat:"housing"},
{id:130,nl:"het balkon",en:"the balcony",example:"Ik zit op het balkon.",cat:"housing"},
{id:131,nl:"de tuin",en:"the garden",example:"De tuin is mooi.",cat:"housing"},
{id:132,nl:"het meubilair",en:"the furniture",example:"Nieuw meubilair.",cat:"housing"},
{id:133,nl:"de bank",en:"the sofa",example:"Zit op de bank.",cat:"housing"},
{id:134,nl:"het bed",en:"the bed",example:"Ik ga naar bed.",cat:"housing"},
{id:135,nl:"de kast",en:"the cupboard",example:"De kleren liggen in de kast.",cat:"housing"},
{id:136,nl:"de koelkast",en:"the fridge",example:"Melk staat in de koelkast.",cat:"housing"},
{id:137,nl:"de wasmachine",en:"the washing machine",example:"De wasmachine is kapot.",cat:"housing"},
{id:138,nl:"de stofzuiger",en:"the vacuum cleaner",example:"Ik gebruik de stofzuiger.",cat:"housing"},
{id:139,nl:"schoonmaken",en:"to clean",example:"Ik maak de kamer schoon.",cat:"housing"},
{id:140,nl:"de huurtoeslag",en:"rent allowance",example:"Ik krijg huurtoeslag.",cat:"housing"},
{id:141,nl:"de pijn",en:"the pain",example:"Ik heb pijn.",cat:"health"},
{id:142,nl:"hoofdpijn",en:"headache",example:"Ik heb hoofdpijn.",cat:"health"},
{id:143,nl:"keelpijn",en:"sore throat",example:"Ik heb keelpijn.",cat:"health"},
{id:144,nl:"koorts",en:"fever",example:"Ik heb koorts.",cat:"health"},
{id:145,nl:"hoesten",en:"to cough",example:"Ik moet hoesten.",cat:"health"},
{id:146,nl:"niezen",en:"to sneeze",example:"Ik nies.",cat:"health"},
{id:147,nl:"de medicijnen",en:"the medicine",example:"Ik neem medicijnen.",cat:"health"},
{id:148,nl:"de tablet",en:"the pill",example:"Neem een tablet.",cat:"health"},
{id:149,nl:"de zalf",en:"the ointment",example:"Smeer de zalf.",cat:"health"},
{id:150,nl:"de injectie",en:"the injection",example:"Ik krijg een injectie.",cat:"health"},
{id:151,nl:"bloedonderzoek",en:"blood test",example:"Ik doe een bloedonderzoek.",cat:"health"},
{id:152,nl:"de röntgenfoto",en:"the X-ray",example:"Ik maak een röntgenfoto.",cat:"health"},
{id:153,nl:"de operatie",en:"the operation",example:"Hij heeft een operatie.",cat:"health"},
{id:154,nl:"genezen",en:"to recover",example:"Ik ben genezen.",cat:"health"},
{id:155,nl:"beter worden",en:"to get better",example:"Ik word beter.",cat:"health"},
{id:156,nl:"de spoedeisende hulp",en:"the ER",example:"Ga naar de spoedeisende hulp.",cat:"health"},
{id:157,nl:"de ambulance",en:"the ambulance",example:"Bel de ambulance.",cat:"health"},
{id:158,nl:"de verpleegkundige",en:"the nurse",example:"De verpleegkundige helpt.",cat:"health"},
{id:159,nl:"zwanger",en:"pregnant",example:"Zij is zwanger.",cat:"health"},
{id:160,nl:"de baby",en:"the baby",example:"De baby huilt.",cat:"health"},
{id:161,nl:"het salarisstrookje",en:"the payslip",example:"Ik krijg mijn salarisstrookje.",cat:"work"},
{id:162,nl:"de vakantie-uren",en:"holiday hours",example:"Ik neem vakantie-uren op.",cat:"work"},
{id:163,nl:"ziekmelden",en:"to call in sick",example:"Ik meld me ziek.",cat:"work"},
{id:164,nl:"de collega",en:"the colleague",example:"Mijn collega is aardig.",cat:"work"},
{id:165,nl:"de baas",en:"the boss",example:"Ik praat met de baas.",cat:"work"},
{id:166,nl:"de vergadering",en:"the meeting",example:"We hebben een vergadering.",cat:"work"},
{id:167,nl:"het kantoor",en:"the office",example:"Ik werk op kantoor.",cat:"work"},
{id:168,nl:"de fabriek",en:"the factory",example:"Hij werkt in de fabriek.",cat:"work"},
{id:169,nl:"de winkel",en:"the shop",example:"Ik werk in een winkel.",cat:"work"},
{id:170,nl:"de klant",en:"the customer",example:"De klant is vriendelijk.",cat:"work"},
{id:171,nl:"verkopen",en:"to sell",example:"Ik verkoop producten.",cat:"work"},
{id:172,nl:"de fulltime",en:"full-time",example:"Ik werk fulltime.",cat:"work"},
{id:173,nl:"de parttime",en:"part-time",example:"Ik werk parttime.",cat:"work"},
{id:174,nl:"de stage",en:"the internship",example:"Ik doe stage.",cat:"work"},
{id:175,nl:"de opleiding",en:"the training",example:"Ik volg een opleiding.",cat:"work"},
{id:176,nl:"promotie",en:"promotion",example:"Ik krijg promotie.",cat:"work"},
{id:177,nl:"ontslag",en:"dismissal",example:"Hij krijgt ontslag.",cat:"work"},
{id:178,nl:"sollicitatiegesprek",en:"job interview",example:"Ik heb een sollicitatiegesprek.",cat:"work"},
{id:179,nl:"de referentie",en:"the reference",example:"Ik vraag een referentie.",cat:"work"},
{id:180,nl:"het netwerk",en:"the network",example:"Een goed netwerk is belangrijk.",cat:"work"},
{id:181,nl:"kopen",en:"to buy",example:"Ik koop brood.",cat:"daily"},
{id:182,nl:"de prijs",en:"the price",example:"Wat is de prijs?",cat:"daily"},
{id:183,nl:"duur",en:"expensive",example:"Dat is duur.",cat:"daily"},
{id:184,nl:"goedkoop",en:"cheap",example:"Dit is goedkoop.",cat:"daily"},
{id:185,nl:"korting",en:"discount",example:"Er is korting.",cat:"daily"},
{id:186,nl:"betalen met pin",en:"pay by card",example:"Ik betaal met pin.",cat:"daily"},
{id:187,nl:"contant",en:"cash",example:"Heb je contant geld?",cat:"daily"},
{id:188,nl:"de kassabon",en:"the receipt",example:"Mag ik de kassabon?",cat:"daily"},
{id:189,nl:"de tas",en:"the bag",example:"Doe het in de tas.",cat:"daily"},
{id:190,nl:"de boodschappen",en:"the groceries",example:"Ik doe boodschappen.",cat:"daily"},
{id:191,nl:"het brood",en:"the bread",example:"Ik koop brood.",cat:"daily"},
{id:192,nl:"de melk",en:"the milk",example:"Ik drink melk.",cat:"daily"},
{id:193,nl:"de kaas",en:"the cheese",example:"Nederlandse kaas.",cat:"daily"},
{id:194,nl:"het fruit",en:"the fruit",example:"Ik eet fruit.",cat:"daily"},
{id:195,nl:"de groente",en:"the vegetables",example:"Eet meer groente.",cat:"daily"},
{id:196,nl:"het vlees",en:"the meat",example:"Ik eet weinig vlees.",cat:"daily"},
{id:197,nl:"de vis",en:"the fish",example:"Verse vis.",cat:"daily"},
{id:198,nl:"het water",en:"the water",example:"Ik drink water.",cat:"daily"},
{id:199,nl:"de koffie",en:"the coffee",example:"Wil je koffie?",cat:"daily"},
{id:200,nl:"de thee",en:"the tea",example:"Ik drink thee.",cat:"daily"},
{id:201,nl:"het ontbijt",en:"the breakfast",example:"Ik eet ontbijt.",cat:"daily"},
{id:202,nl:"de lunch",en:"the lunch",example:"Tijd voor lunch.",cat:"daily"},
{id:203,nl:"het diner",en:"the dinner",example:"We eten diner.",cat:"daily"},
{id:204,nl:"koken",en:"to cook",example:"Ik kook graag.",cat:"daily"},
{id:205,nl:"eten",en:"to eat",example:"Ik eet appels.",cat:"daily"},
{id:206,nl:"drinken",en:"to drink",example:"Ik drink water.",cat:"daily"},
{id:207,nl:"honger",en:"hunger",example:"Ik heb honger.",cat:"daily"},
{id:208,nl:"dorst",en:"thirst",example:"Ik heb dorst.",cat:"daily"},
{id:209,nl:"lekker",en:"tasty",example:"Het is lekker.",cat:"daily"},
{id:210,nl:"de politie",en:"the police",example:"Bel de politie.",cat:"daily"},
{id:211,nl:"de brandweer",en:"the fire brigade",example:"De brandweer komt.",cat:"daily"},
{id:212,nl:"de leraar",en:"the teacher",example:"De leraar legt uit.",cat:"daily"},
{id:213,nl:"de lerares",en:"the teacher (f)",example:"De lerares is aardig.",cat:"daily"},
{id:214,nl:"de leerling",en:"the pupil",example:"De leerling leert.",cat:"daily"},
{id:215,nl:"het huiswerk",en:"the homework",example:"Ik maak huiswerk.",cat:"daily"},
{id:216,nl:"de toets",en:"the test",example:"Morgen is er een toets.",cat:"daily"},
{id:217,nl:"het examen",en:"the exam",example:"Ik doe examen.",cat:"daily"},
{id:218,nl:"zakken",en:"to fail",example:"Ik ben gezakt.",cat:"daily"},
{id:219,nl:"slagen",en:"to pass",example:"Ik ben geslaagd.",cat:"daily"},
{id:220,nl:"leren",en:"to learn",example:"Ik leer Nederlands.",cat:"daily"},
{id:221,nl:"studeren",en:"to study",example:"Ik studeer hard.",cat:"daily"},
{id:222,nl:"de cursus",en:"the course",example:"Ik doe een cursus.",cat:"daily"},
{id:223,nl:"de les",en:"the lesson",example:"De les begint.",cat:"daily"},
{id:224,nl:"het boek",en:"the book",example:"Ik lees een boek.",cat:"daily"},
{id:225,nl:"de krant",en:"the newspaper",example:"Ik lees de krant.",cat:"daily"},
{id:226,nl:"het nieuws",en:"the news",example:"Ik kijk het nieuws.",cat:"daily"},
{id:227,nl:"de televisie",en:"the television",example:"Ik kijk televisie.",cat:"daily"},
{id:228,nl:"de film",en:"the film",example:"We kijken een film.",cat:"daily"},
{id:229,nl:"de muziek",en:"the music",example:"Ik luister naar muziek.",cat:"daily"},
{id:230,nl:"sporten",en:"to do sports",example:"Ik sport graag.",cat:"daily"},
{id:231,nl:"wandelen",en:"to walk",example:"Ik ga wandelen.",cat:"daily"},
{id:232,nl:"fietsen",en:"to cycle",example:"Ik fiets naar het werk.",cat:"daily"},
{id:233,nl:"zwemmen",en:"to swim",example:"Ik kan zwemmen.",cat:"daily"},
{id:234,nl:"de sportschool",en:"the gym",example:"Ik ga naar de sportschool.",cat:"daily"},
{id:235,nl:"moe",en:"tired",example:"Ik ben moe.",cat:"daily"},
{id:236,nl:"blij",en:"happy",example:"Ik ben blij.",cat:"daily"},
{id:237,nl:"boos",en:"angry",example:"Hij is boos.",cat:"daily"},
{id:238,nl:"verdrietig",en:"sad",example:"Zij is verdrietig.",cat:"daily"},
{id:239,nl:"bang",en:"afraid",example:"Ik ben bang.",cat:"daily"},
{id:240,nl:"nerveus",en:"nervous",example:"Ik ben nerveus.",cat:"daily"},
{id:241,nl:"kalm",en:"calm",example:"Blijf kalm.",cat:"daily"},
{id:242,nl:"behulpzaam",en:"helpful",example:"Hij is behulpzaam.",cat:"daily"},
{id:243,nl:"eerlijk",en:"honest",example:"Wees eerlijk.",cat:"daily"},
{id:244,nl:"geduldig",en:"patient",example:"Wees geduldig.",cat:"daily"},
{id:245,nl:"druk",en:"busy",example:"Ik ben druk.",cat:"daily"},
{id:246,nl:"bezig",en:"occupied",example:"Ik ben bezig.",cat:"daily"},
{id:247,nl:"klaar",en:"ready",example:"Ik ben klaar.",cat:"daily"},
{id:248,nl:"beginnen",en:"to start",example:"We beginnen.",cat:"daily"},
{id:249,nl:"stoppen",en:"to stop",example:"Stop alsjeblieft.",cat:"daily"},
{id:250,nl:"wachten",en:"to wait",example:"Ik wacht op je.",cat:"daily"},
{id:251,nl:"komen",en:"to come",example:"Kom hier.",cat:"daily"},
{id:252,nl:"gaan",en:"to go",example:"Ik ga naar huis.",cat:"daily"},
{id:253,nl:"blijven",en:"to stay",example:"Ik blijf thuis.",cat:"daily"},
{id:254,nl:"vertrekken",en:"to depart",example:"De trein vertrekt.",cat:"daily"},
{id:255,nl:"reizen",en:"to travel",example:"Ik reis graag.",cat:"daily"},
{id:256,nl:"de reis",en:"the journey",example:"Goede reis!",cat:"daily"},
{id:257,nl:"het ticket",en:"the ticket",example:"Ik koop een ticket.",cat:"daily"},
{id:258,nl:"de bagage",en:"the luggage",example:"Mijn bagage is zwaar.",cat:"daily"},
{id:259,nl:"het hotel",en:"the hotel",example:"We slapen in een hotel.",cat:"daily"},
{id:260,nl:"zonnig",en:"sunny",example:"Het is zonnig.",cat:"daily"},
{id:261,nl:"bewolkt",en:"cloudy",example:"Het is bewolkt.",cat:"daily"},
{id:262,nl:"regenachtig",en:"rainy",example:"Het is regenachtig.",cat:"daily"},
{id:263,nl:"winderig",en:"windy",example:"Het is winderig.",cat:"daily"},
{id:264,nl:"koud",en:"cold",example:"Het is koud.",cat:"daily"},
{id:265,nl:"warm",en:"warm",example:"Het is warm.",cat:"daily"},
{id:266,nl:"heet",en:"hot",example:"Het is heet.",cat:"daily"},
{id:267,nl:"de temperatuur",en:"the temperature",example:"Wat is de temperatuur?",cat:"daily"},
{id:268,nl:"de lente",en:"the spring",example:"In de lente bloeien bloemen.",cat:"daily"},
{id:269,nl:"de zomer",en:"the summer",example:"In de zomer is het warm.",cat:"daily"},
{id:270,nl:"de herfst",en:"the autumn",example:"In de herfst vallen bladeren.",cat:"daily"},
{id:271,nl:"de winter",en:"the winter",example:"In de winter sneeuwt het.",cat:"daily"},
{id:272,nl:"de sneeuw",en:"the snow",example:"Er ligt sneeuw.",cat:"daily"},
{id:273,nl:"de regen",en:"the rain",example:"De regen valt.",cat:"daily"},
{id:274,nl:"de wind",en:"the wind",example:"De wind is hard.",cat:"daily"},
{id:275,nl:"de zon",en:"the sun",example:"De zon schijnt.",cat:"daily"},
{id:276,nl:"de dag",en:"the day",example:"Goede dag!",cat:"daily"},
{id:277,nl:"de nacht",en:"the night",example:"Goede nacht!",cat:"daily"},
{id:278,nl:"de ochtend",en:"the morning",example:"Goedemorgen!",cat:"daily"},
{id:279,nl:"de middag",en:"the afternoon",example:"Goedemiddag!",cat:"daily"},
{id:280,nl:"de avond",en:"the evening",example:"Goedenavond!",cat:"daily"},
{id:281,nl:"vandaag",en:"today",example:"Vandaag is het mooi.",cat:"daily"},
{id:282,nl:"morgen",en:"tomorrow",example:"Tot morgen!",cat:"daily"},
{id:283,nl:"gisteren",en:"yesterday",example:"Gisteren was ik ziek.",cat:"daily"},
{id:284,nl:"nu",en:"now",example:"Nu ga ik.",cat:"daily"},
{id:285,nl:"later",en:"later",example:"Tot later!",cat:"daily"},
{id:286,nl:"vroeg",en:"early",example:"Ik sta vroeg op.",cat:"daily"},
{id:287,nl:"laat",en:"late",example:"Het is laat.",cat:"daily"},
{id:288,nl:"altijd",en:"always",example:"Ik kom altijd op tijd.",cat:"daily"},
{id:289,nl:"nooit",en:"never",example:"Ik ben nooit te laat.",cat:"daily"},
{id:290,nl:"soms",en:"sometimes",example:"Soms regent het.",cat:"daily"},
{id:291,nl:"vaak",en:"often",example:"Ik fiets vaak.",cat:"daily"},
{id:292,nl:"meestal",en:"usually",example:"Meestal eet ik thuis.",cat:"daily"},
{id:293,nl:"misschien",en:"maybe",example:"Misschien kom ik.",cat:"daily"},
{id:294,nl:"natuurlijk",en:"of course",example:"Natuurlijk help ik je.",cat:"daily"},
{id:295,nl:"graag",en:"gladly",example:"Ja, graag!",cat:"daily"},
{id:296,nl:"alsjeblieft",en:"please",example:"Help me alsjeblieft.",cat:"daily"},
{id:297,nl:"dank je wel",en:"thank you",example:"Dank je wel!",cat:"daily"},
{id:298,nl:"sorry",en:"sorry",example:"Sorry, ik ben te laat.",cat:"daily"},
{id:299,nl:"geen probleem",en:"no problem",example:"Geen probleem!",cat:"daily"},
{id:300,nl:"tot ziens",en:"goodbye",example:"Tot ziens!",cat:"daily"},
{id:301,nl:"tot straks",en:"see you later",example:"Tot straks!",cat:"daily"},
{id:302,nl:"tot morgen",en:"see you tomorrow",example:"Tot morgen!",cat:"daily"},
{id:303,nl:"welterusten",en:"good night",example:"Welterusten!",cat:"daily"},
{id:304,nl:"goedemorgen",en:"good morning",example:"Goedemorgen!",cat:"daily"},
{id:305,nl:"de buurt",en:"the neighbourhood",example:"Ik woon in deze buurt.",cat:"daily"},
{id:306,nl:"de straat",en:"the street",example:"Ik woon in deze straat.",cat:"daily"},
{id:307,nl:"het nummer",en:"the number",example:"Wat is je nummer?",cat:"daily"},
{id:308,nl:"het adres",en:"the address",example:"Wat is je adres?",cat:"daily"},
{id:309,nl:"de postcode",en:"the postcode",example:"Mijn postcode is 1234 AB.",cat:"daily"},
{id:310,nl:"de stad",en:"the city",example:"Ik woon in de stad.",cat:"daily"},
{id:311,nl:"het dorp",en:"the village",example:"Ik woon in een dorp.",cat:"daily"},
{id:312,nl:"het centrum",en:"the centre",example:"Het centrum is druk.",cat:"daily"},
{id:313,nl:"de markt",en:"the market",example:"Ik ga naar de markt.",cat:"daily"},
{id:314,nl:"het park",en:"the park",example:"We wandelen in het park.",cat:"daily"}
];

const GRAMMAR_LESSONS = [];
for(let i=1;i<=20;i++){
  const titles = ["de/het/een","Word order","Present tense","Modal verbs","Perfectum","Separable verbs","omdat/want/maar","Formele e-mail","Possessive","Demonstratives","Comparatives","Imperative","Reflexive verbs","Er + preposition","Relative die/dat","Indirect speech intro","Time expressions","Prepositions of place","Negation niet/geen","Questions with inversion"];
  const contents = [
    "de = common gender + all plurals. het = neuter. een = a/an.",
    "Verb in second position in main clauses. In questions verb first.",
    "ik werk, jij werkt, hij werkt, wij werken. Stem + ending.",
    "kunnen/moeten/willen/mogen. Main verb to the end.",
    "hebben/zijn + past participle. Ik heb gewerkt. Ik ben gegaan.",
    "opstaan → ik sta op. Prefix separates in main clause.",
    "omdat = because (subordinate). want = because (main). maar = but.",
    "Geachte... / Met vriendelijke groet. Use 'u'.",
    "mijn, jouw, zijn, haar, ons, jullie, hun.",
    "deze/dit (this), die/dat (that).",
    "groter dan, even groot als, de grootste.",
    "Kom hier! Ga zitten! No subject needed.",
    "zich wassen, zich haasten. Ik was me.",
    "Ik wacht erop. Er + preposition for 'it'.",
    "de man die... , het huis dat...",
    "Hij zegt dat hij komt. Verb to the end.",
    "vandaag, gisteren, morgen, nu, straks, al, nog.",
    "in, op, onder, naast, tussen, voor, achter.",
    "niet after verb. geen before noun.",
    "Woon je...? Gaat hij...? Inversion in questions."
  ];
  GRAMMAR_LESSONS.push({
    id:"g"+i, title:(i)+". "+titles[i-1], level:"A2",
    content:"<div class='theory-card'><h3>"+titles[i-1]+"</h3><p>"+contents[i-1]+"</p></div>",
    quiz:[{q:"Check your understanding of "+titles[i-1],options:["I understand","Need more practice","Review later"],correct:0}]
  });
}

const LISTENING_ITEMS = [];
const listenBase = [
  {t:"Telefoongesprek huisarts",tx:"Goedemorgen, huisartsenpraktijk. Ik wil een afspraak maken. Ik heb keelpijn. Morgen om half elf kan. Ja, dat is goed. Tot morgen."},
  {t:"Verhuurder over verwarming",tx:"Hier spreekt de verhuurder. De monteur komt woensdag tussen 10 en 12. Zorg dat er iemand thuis is."},
  {t:"Vacature supermarkt",tx:"Wij zoeken een medewerker 24-32 uur. Ervaring niet nodig. Minimaal A2 Nederlands. Solliciteer via de website."},
  {t:"Afval scheiden",tx:"GFT in de groene bak. Plastic in de oranje bak. Papier blauw. Restafval grijs. Verkeerd scheiden geeft boete van 90 euro."},
  {t:"Sollicitatiegesprek",tx:"Vertel over jezelf. Ik wil in de zorg werken. Ik ben flexibel en vriendelijk. We bellen je volgende week."},
  {t:"Gemeente afspraak",tx:"Ik wil een afspraak voor DigiD. Ik kan dinsdag of donderdag. U krijgt een bevestiging per e-mail."},
  {t:"School bericht",tx:"Uw kind is ziek gemeld. Hij kan morgen weer komen als hij beter is. Bel bij vragen."},
  {t:"Treinvertraging",tx:"De trein naar Utrecht heeft 15 minuten vertraging. Excuses voor het ongemak."},
  {t:"Apotheek",tx:"Uw medicijnen zijn klaar. U kunt ze vandaag ophalen. Neem uw paspoort mee."},
  {t:"Huurverhoging",tx:"Vanaf 1 juli stijgt de huur met 2,5 procent. De nieuwe huur is 875 euro."},
  {t:"Buren ruzie",tx:"Er is een probleem met de schutting. Laten we samen praten om een oplossing te vinden."},
  {t:"Werk.nl",tx:"Op Werk.nl vindt u vacatures. Maak een account en upload uw CV."},
  {t:"Toeslag aanvraag",tx:"U heeft zorgtoeslag aangevraagd. Stuur binnen 3 weken een kopie van uw polis."},
  {t:"Koningsdag",tx:"Op 27 april is Koningsdag. Overal is het oranje en zijn er vrijmarkten."},
  {t:"Huisartsenpost",tx:"Buiten kantooruren belt u de huisartsenpost. Bij spoed belt u 112."},
  {t:"Contract tekenen",tx:"U tekent vandaag het tijdelijke contract voor 6 maanden. Daarna kan het vast worden."},
  {t:"Bibliotheek",tx:"U kunt gratis lid worden van de bibliotheek. Neem een identiteitsbewijs mee."},
  {t:"Fietsen",tx:"In Nederland fietsen veel mensen. Er zijn aparte fietspaden. Let op de regels."},
  {t:"UWV",tx:"Bij werkloosheid meldt u zich bij het UWV. U kunt WW aanvragen als u voldoet aan de voorwaarden."},
  {t:"Ouderavond",tx:"Op 12 maart is er ouderavond over de overstap naar het voortgezet onderwijs. Aanmelden via de app."}
];
listenBase.forEach((b,i)=>{
  LISTENING_ITEMS.push({
    id:"l"+(i+1), title:b.t, level:"A2", text:b.tx,
    questions:[
      {q:"Wat is het onderwerp?",options:["Werk","Gezondheid of wonen of dagelijks leven","Sport","Vakantie"],correct:1},
      {q:"Is de informatie duidelijk?",options:["Ja","Nee","Gedeeltelijk","Onbekend"],correct:0},
      {q:"Wat moet je vooral onthouden?",options:["De kernboodschap","Alleen de datum","Niets","Alleen de naam"],correct:0}
    ]
  });
});

const READING_TEXTS = [];
const readBase = [
  {t:"Brief verhuurder",tx:"Geachte heer/mevrouw, vanaf 1 juli stijgt de huur met 2,5%. Nieuwe huur 875 euro. Vragen? Mail of bel."},
  {t:"Huisarts uitslag",tx:"Uw bloedonderzoek is in orde. Beweeg meer en eet minder zout. Over 3 maanden controle."},
  {t:"Vacature",tx:"Medewerker klantenservice 32-40 uur. A2 Nederlands. Ervaring niet nodig. Solliciteer voor 15 maart."},
  {t:"Afval",tx:"GFT groen, plastic oranje, papier blauw, rest grijs. Boete 90 euro bij verkeerd scheiden."},
  {t:"Ouderavond",tx:"12 maart 19.30 ouderavond over VMBO HAVO VWO. Aanmelden voor 5 maart."},
  {t:"Toeslag",tx:"Zorgtoeslag aangevraagd. Stuur kopie polis binnen 3 weken via DigiD."},
  {t:"School ziek",tx:"Uw kind is ziek gemeld. Morgen weer welkom als beter. Bel bij vragen."},
  {t:"Trein",tx:"Trein naar Amsterdam 10 minuten later. Excuses voor het ongemak."},
  {t:"Apotheek",tx:"Medicijnen klaar. Ophalen met identiteitsbewijs."},
  {t:"Gemeente",tx:"Afspraak DigiD bevestigd voor dinsdag 10.00. Neem paspoort mee."},
  {t:"Contract",tx:"Tijdelijk contract 6 maanden. Daarna evaluatie voor vast contract."},
  {t:"Bibliotheek",tx:"Gratis lidmaatschap. Neem ID mee. Boeken lenen voor 3 weken."},
  {t:"WW info",tx:"Bij ontslag meld u bij UWV. Check of u recht heeft op WW."},
  {t:"Koningsdag",tx:"27 april Koningsdag. Vrijmarkt en oranje kleding overal."},
  {t:"Huisartsenpost",tx:"Buiten openingstijden: huisartsenpost. Spoed: 112."},
  {t:"Buren",tx:"Probleem met schutting. Laten we een afspraak maken om te praten."},
  {t:"Sollicitatie",tx:"Bedankt voor uw sollicitatie. We bellen u volgende week voor een gesprek."},
  {t:"Huurtoeslag",tx:"Huurtoeslag aangevraagd. U krijgt bericht binnen 5 weken."},
  {t:"Fiets",tx:"Nieuwe fietspaden in de wijk. Let op de borden en voorrang."},
  {t:"Diploma",tx:"Gefeliciteerd met uw diploma. U kunt zich nu inschrijven voor vervolgopleiding."}
];
readBase.forEach((b,i)=>{
  READING_TEXTS.push({
    id:"r"+(i+1), title:b.t, level:"A2", text:b.tx,
    questions:[
      {q:"Wat is de hoofdboodschap?",options:["Iets positiefs of informatiefs","Alleen een klacht","Niets belangrijks","Alleen een datum"],correct:0},
      {q:"Wat moet de lezer doen?",options:["Actie ondernemen of informeren","Niets","Alleen lezen","Weggooien"],correct:0},
      {q:"Is de toon formeel?",options:["Ja meestal","Nee","Alleen informeel","Onbekend"],correct:0}
    ]
  });
});

const WRITING_TASKS = [];
const writeBase = [
  {t:"E-mail verhuurder",p:"Schrijf e-mail: verwarming doet het niet. Vraag om monteur.",k:["verwarming","komen","kijken","probleem","koud"],m:40},
  {t:"Klacht product",p:"Lamp kapot aangekomen. Order 458921. Vraag nieuw of geld terug.",k:["kapot","ordernummer","nieuw","geld"],m:30},
  {t:"School ziek",p:"Kind ziek, kan niet naar school. Morgen hopelijk weer.",k:["ziek","school","kind","morgen"],m:25},
  {t:"Motivatie sollicitatie",p:"Vakkenvuller. Flexibel, vriendelijk, snel beginnen.",k:["solliciteer","flexibel","vriendelijk","beginnen"],m:40},
  {t:"Afspraak gemeente",p:"Afspraak DigiD. Beschikbaar dinsdag/donderdag.",k:["afspraak","DigiD","dinsdag","donderdag"],m:30},
  {t:"Bedankmail",p:"Bedank voor het gesprek. Je bent nog steeds geïnteresseerd.",k:["bedankt","gesprek","geïnteresseerd"],m:25},
  {t:"Klacht buren",p:"Buren maken te veel lawaai. Vraag om rust na 22.00.",k:["lawaai","buren","rust","22"],m:30},
  {t:"Aanvraag toeslag",p:"Vraag om hulp bij zorgtoeslag aanvraag.",k:["toeslag","hulp","DigiD","aanvraag"],m:30},
  {t:"Ziekmelden werk",p:"Je bent ziek en kunt niet werken. Informeer werkgever.",k:["ziek","werken","afwezig"],m:25},
  {t:"Uitnodiging",p:"Nodig collega uit voor koffie om te netwerken.",k:["uitnodigen","koffie","netwerk"],m:25},
  {t:"Verhuizing melden",p:"Meld verhuizing aan gemeente. Nieuwe adres geven.",k:["verhuizing","adres","gemeente"],m:30},
  {t:"Vraag over contract",p:"Vraag wanneer tijdelijk contract vast kan worden.",k:["contract","vast","wanneer"],m:25},
  {t:"Afspraak huisarts",p:"Maak afspraak voor keelpijn. Geef beschikbaarheid.",k:["afspraak","huisarts","keelpijn"],m:25},
  {t:"Feedback geven",p:"Geef korte positieve feedback na een cursus.",k:["bedankt","geleerd","nuttig"],m:25},
  {t:"Vraag om referentie",p:"Vraag vorige werkgever om een referentie.",k:["referentie","werkgever","vriendelijk"],m:30},
  {t:"Bevestiging afspraak",p:"Bevestig afspraak met monteur woensdag 10-12.",k:["bevestig","afspraak","woensdag"],m:20},
  {t:"Klacht treinen",p:"Klacht over frequente vertragingen naar werk.",k:["vertraging","trein","werk"],m:30},
  {t:"Aanmelden cursus",p:"Meld je aan voor taalcursus A2. Vraag info over dagen.",k:["aanmelden","cursus","A2"],m:25},
  {t:"Bedankt voor hulp",p:"Bedank iemand die je geholpen heeft met DigiD.",k:["bedankt","hulp","DigiD"],m:20},
  {t:"Open sollicitatie",p:"Korte open sollicitatie voor zorgfunctie.",k:["solliciteer","zorg","ervaring","flexibel"],m:40}
];
writeBase.forEach((b,i)=>{
  WRITING_TASKS.push({
    id:"w"+(i+1), title:b.t, type:"A2 task",
    prompt:b.p, keywords:b.k, minWords:b.m,
    model:"Geachte heer/mevrouw,\n\n[Uw tekst hier]\n\nMet vriendelijke groet,\n[Naam]",
    checklist:["Begroeting","Duidelijke boodschap","Vriendelijke toon","Afsluiting + naam"]
  });
});

const SPEAKING_PROMPTS = [];
const speakBase = [
  {t:"Jezelf voorstellen",s:"Stel jezelf voor.",k:["heet","kom uit","woon","werk"]},
  {t:"Probleem woning",s:"Beschrijf een probleem in huis.",k:["probleem","lekkage","verwarming","verhuurder"]},
  {t:"Afspraak maken",s:"Maak een afspraak bij de dokter.",k:["afspraak","huisarts","beschikbaar"]},
  {t:"Over werk praten",s:"Vertel over je werk of gewenste werk.",k:["werk","ervaring","wil","flexibel"]},
  {t:"Mening geven",s:"Geef je mening over een situatie.",k:["vind","volgens mij","omdat"]},
  {t:"Dagelijkse routine",s:"Vertel over een gewone dag.",k:["opstaan","werken","avond"]},
  {t:"Vrije tijd",s:"Wat doe je in je vrije tijd?",k:["hobby","graag","weekend"]},
  {t:"Familie",s:"Vertel over je familie.",k:["familie","kinderen","ouders"]},
  {t:"Wonen",s:"Beschrijf je woning en buurt.",k:["woning","buren","buurt"]},
  {t:"Gezondheid",s:"Vertel wat je doet als je ziek bent.",k:["ziek","huisarts","rust"]},
  {t:"Boodschappen",s:"Vertel hoe je boodschappen doet.",k:["supermarkt","boodschappen","kopen"]},
  {t:"Vervoer",s:"Hoe ga je naar werk of school?",k:["fiets","bus","trein"]},
  {t:"Feestdagen",s:"Vertel over een Nederlandse feestdag.",k:["Koningsdag","Sinterklaas","vieren"]},
  {t:"Toekomst",s:"Wat wil je over 2 jaar doen?",k:["wil","werken","leren"]},
  {t:"Hulp vragen",s:"Vraag om hulp in een winkel.",k:["helpen","waar","zoek"]},
  {t:"Klacht uiten",s:"Uit een beleefde klacht.",k:["probleem","graag","oplossen"]},
  {t:"Netwerken",s:"Stel jezelf voor op een netwerkevenement.",k:["naam","werk","interessant"]},
  {t:"Advies geven",s:"Geef advies aan iemand die net aankomt.",k:["raad","belangrijk","leren"]},
  {t:"Vergelijken",s:"Vergelijk je oude land met Nederland.",k:["anders","hier","daar"]},
  {t:"Doelen",s:"Wat zijn je leerdoelen voor Nederlands?",k:["leren","beter","examen"]}
];
speakBase.forEach((b,i)=>{
  SPEAKING_PROMPTS.push({
    id:"s"+(i+1), title:b.t, situation:b.s,
    tasks:["Spreek 4-6 zinnen","Gebruik relevante woorden","Spreek duidelijk"],
    keywords:b.k,
    example:"Dit is een voorbeeldantwoord. Oefen hardop en gebruik eenvoudige zinnen."
  });
});

const KNM_TOPICS = [
{id:"k1",title:"Wonen",points:["Sociale huur vs vrije sector","Afval scheiden verplicht","BRP inschrijving bij verhuizen","OZB betaalt eigenaar","Huurcontract is belangrijk"]},
{id: "k2",title:"Gezondheidszorg",points:["Eerst huisarts","Eigen risico","Verloskundige bij zwangerschap","Huisartsenpost buiten uren","112 bij spoed"]},
{id:"k3",title:"Werk & inkomen",points:["Vast vs tijdelijk contract","WW via UWV","Toeslagen via Belastingdienst","CAO","Minimumloon"]},
{id:"k4",title:"Overheid & DigiD",points:["DigiD voor overheid","Koning ceremonieel","Stemmen vanaf 18","Artikel 1 Grondwet","Gemeente, DUO, IND, UWV"]},
{id:"k5",title:"Onderwijs",points:["Leerplicht vanaf 5","VMBO HAVO VWO","HBO en universiteit","Schoolkeuzevrijheid"]},
{id:"k6",title:"Geschiedenis & waarden",points:["WO II en Bevrijding","4 mei en 5 mei","Vrijheid van meningsuiting","Gelijkheid","Democratie"]},
{id:"k7",title:"Dagelijks leven",points:["Op tijd komen","Directe communicatie","Fietsen","Koningsdag en Sinterklaas","Afspraken maken"]},
{id:"k8",title:"Werkcultuur",points:["Platte hiërarchie","Vergaderen","Werk-privé balans","Eerlijkheid","Initiatief tonen"]}
];

const KNM_QUESTIONS = [];
const knmQBase = [
{q:"Eerst naar specialist of huisarts?",o:["Specialist","Huisarts","112","Apotheek"],c:1,e:"Eerst huisarts."},
{q:"Wat is DigiD?",o:["Bankpas","Digitale ID overheid","Verzekering","Rijbewijs"],c:1,e:"Login voor overheid."},
{q:"Eigen risico is?",o:["Gratis zorg","Eerste kosten zelf betalen","Alleen tandarts","Voor kinderen"],c:1,e:"Je betaalt eerste deel zelf."},
{q:"GFT bak kleur?",o:["Grijs","Groen","Blauw","Oranje"],c:1,e:"Groen."},
{q:"Rol Koning?",o:["Wetten maken","Ceremonieel","Premier","Politiebaas"],c:1,e:"Ceremonieel."},
{q:"Leerplicht vanaf?",o:["4","5","6","7"],c:1,e:"5 jaar."},
{q:"Tweede Kamer is?",o:["Paleis","Parlement","Rechtbank","Gemeente"],c:1,e:"Parlement."},
{q:"Vast contract is?",o:["1 jaar","Onbepaalde tijd","Stage","ZZP"],c:1,e:"Onbepaalde tijd."},
{q:"Dodenherdenking?",o:["4 mei","5 mei","27 april","5 dec"],c:0,e:"4 mei."},
{q:"Artikel 1?",o:["Taal leren","Gelijkheid geen discriminatie","Koning","Godsdienst"],c:1,e:"Gelijkheid."},
{q:"OZB betaalt?",o:["Huurder","Eigenaar","Iedereen","Bedrijf"],c:1,e:"Eigenaar."},
{q:"Huisartsenpost?",o:["Ziekenhuis","Buiten kantooruren","Tandarts","Apotheek"],c:1,e:"Buiten uren."},
{q:"CAO is?",o:["Belasting","Collectieve arbeidsovereenkomst","Diploma","Uitkering"],c:1,e:"Afspraken per sector."},
{q:"Huurtoeslag waar?",o:["Gemeente","Belastingdienst DigiD","DUO","Verhuurder"],c:1,e:"Belastingdienst."},
{q:"Nederlandse omgang?",o:["Indirect","Direct en op tijd","Zomaar binnen","Altijd u"],c:1,e:"Direct en stipt."},
{q:"Naar universiteit?",o:["VMBO","HAVO","VWO","MBO2"],c:2,e:"VWO."},
{q:"Belastingdienst doet?",o:["Politie","Belasting en toeslagen","Immigratie","Onderwijs"],c:1,e:"Belasting + toeslagen."},
{q:"Discriminatie mag?",o:["Ja privé","Nee verboden","Alleen werk","Meerderheid"],c:1,e:"Verboden."},
{q:"Polder is?",o:["Kaas","Drooggelegd land","Huis","Feestdag"],c:1,e:"Land onder zeeniveau."},
{q:"Koningsdag?",o:["5 mei","27 april","4 mei","5 dec"],c:1,e:"27 april."},
{q:"Bij ziekte eerst?",o:["112","Huisarts","Ziekenhuis","Specialist"],c:1,e:"Huisarts."},
{q:"WW bij?",o:["Gemeente","UWV","DUO","Belastingdienst"],c:1,e:"UWV."},
{q:"Stemmen vanaf?",o:["16","18","21","25"],c:1,e:"18."},
{q:"Sociale huur?",o:["Duur","Goedkoper met wachtlijst","Koop","Tijdelijk"],c:1,e:"Gesubsidieerd."},
{q:"5 mei is?",o:["Herdenking","Bevrijdingsdag","Koningsdag","Sinterklaas"],c:1,e:"Bevrijding."},
{q:"Verloskundige voor?",o:["Tanden","Zwangerschap","Ogen","Huid"],c:1,e:"Zwangerschap."},
{q:"Platte hiërarchie betekent?",o:["Strenge baas","Weinig niveaus, open communicatie","Geen baas","Alleen formeel"],c:1,e:"Open en weinig lagen."},
{q:"Werk.nl is voor?",o:["Belasting","Vacatures en werk", "School","Zorg"],c:1,e:"Vacatures."},
{q:"Boete verkeerd afval?",o:["Geen","Waarschuwing","Rond 90 euro","Gevangenis"],c:2,e:"Ongeveer 90 euro."},
{q:"DigiD nodig voor?",o:["Alleen bank","Overheid toeslagen DUO etc","Alleen school","Niets"],c:1,e:"Overheidszaken."},
{q:"VMBO is?",o:["Universiteit","Praktisch/beroepsgericht","Alleen theorie","HBO"],c:1,e:"Beroepsgericht."},
{q:"Op tijd komen is?",o:["Niet belangrijk","Heel belangrijk","Alleen op werk","Alleen school"],c:1,e:"Zeer belangrijk."},
{q:"112 voor?",o:["Huisarts","Spoed ambulance brandweer politie","Apotheek","Gemeente"],c:1,e:"Spoed."},
{q:"Tijdelijk contract kan?",o:["Nooit vast","Na periode vaak vast worden","Alleen 1 week","Alleen stage"],c:1,e:"Kan vast worden."},
{q:"Sinterklaas is in?",o:["April","December","Mei","Juli"],c:1,e:"December."},
{q:"Gelijkheid staat in?",o:["CAO","Grondwet artikel 1","Huurcontract","Diploma"],c:1,e:"Grondwet."},
{q:"Fietsen in NL?",o:["Verboden","Heel normaal en veilig met paden","Alleen sport","Duur"],c:1,e:"Dagelijks en normaal."},
{q:"Toeslagen aanvragen met?",o:["Brief","DigiD","Telefoon alleen","Paspoort alleen"],c:1,e:"DigiD."},
{q:"Premier is?",o:["Koning","Leider van de regering","Burgemeester","Rechter"],c:1,e:"Regeringsleider."},
{q:"Na basisschool keuzes?",o:["Alleen universiteit","VMBO HAVO VWO","Alleen werk","Geen keuze"],c:1,e:"VMBO/HAVO/VWO."}
];
knmQBase.forEach((b,i)=>{
  KNM_QUESTIONS.push({q:b.q, options:b.o, correct:b.c, expl:b.e});
});

const PATH_MODULES = [];
for(let i=1;i<=12;i++){
  PATH_MODULES.push({
    id:"m"+i,
    title:"Module "+i,
    desc:"Oefen de bijbehorende skills en markeer als klaar.",
    skills:["vocab","grammar","listening","reading","writing","speaking","knm"][i%7] ? ["mixed"] : ["mixed"]
  });
}

const ONA_CONTENT = `
<div class="card info">
  <h2>ONA Muafiyet / Exemption</h2>
  <p>Sommige mensen zijn vrijgesteld van ONA (bijvoorbeeld als je al voldoende gewerkt hebt in Nederland).</p>
  <p>Check altijd in <strong>Mijn Inburgering</strong> of jij muaf bent.</p>
  <button class="btn success" id="ona-exempt-btn" style="margin-top:12px">✅ Ben ONA’dan muafım – İşaretle</button>
  <div id="ona-exempt-status" style="margin-top:10px;font-weight:600"></div>
</div>
<div class="card">
  <h2>Wat is ONA?</h2>
  <p>Portfolio met 8 resultaatkaarten + eindgesprek of 64-uurs cursus. Geen traditioneel examen.</p>
</div>
<div class="card">
  <h2>De 8 Resultaatkaarten</h2>
  <div class="ona-cards">
    <div class="ona-card"><strong>1.</strong> Loopbaanoriëntatie</div>
    <div class="ona-card"><strong>2.</strong> Realistisch beroepsperspectief</div>
    <div class="ona-card"><strong>3.</strong> Persoonlijke kwaliteiten</div>
    <div class="ona-card"><strong>4.</strong> Banenkansen</div>
    <div class="ona-card"><strong>5.</strong> Competenties</div>
    <div class="ona-card"><strong>6.</strong> Netwerken</div>
    <div class="ona-card"><strong>7.</strong> Sollicitatie-activiteiten</div>
    <div class="ona-card"><strong>8.</strong> Werkcultuur & ontwikkelplan</div>
  </div>
</div>
<div class="card">
  <h2>Tips</h2>
  <ul>
    <li>Schrijf in eenvoudig A2 Nederlands</li>
    <li>Voeg bewijzen toe (screenshots, e-mails)</li>
    <li>Ken je kaarten voor het gesprek</li>
  </ul>
</div>
`;
