// A2 (inburgeringsexamen) source bank: listening scripts read aloud by the speech synthesiser.
// Types: omroep (8), voicemail (8), gesprek (10), telefoon (8), bericht (6).

export const LUISTEREN = [
  {
    id: 'a2l01',
    type: 'omroep',
    script: `Dames en heren, uw aandacht alstublieft. De intercity naar Utrecht Centraal van veertien uur tien vertrekt vandaag niet van spoor vijf, maar van spoor acht. Ik herhaal: spoor acht. De trein heeft ook een vertraging van tien minuten. Reizigers naar Amersfoort kunnen in Utrecht overstappen op spoor elf. Houd uw vervoersbewijs bij de hand, want er is vandaag controle op het station. Wij wensen u een goede reis.`,
    qs: [
      { q: 'Waar hoor je dit bericht?', o: ['In de bus', 'Op het station', 'Op het vliegveld'], a: 1 },
      { q: 'Van welk spoor vertrekt de trein naar Utrecht?', o: ['Spoor vijf', 'Spoor elf', 'Spoor acht'], a: 2 },
      { q: 'Hoeveel vertraging heeft de trein?', o: ['Tien minuten', 'Vijf minuten', 'Een uur'], a: 0 },
      { q: 'Wat moeten reizigers bij de hand houden?', o: ['Hun bagage', 'Hun vervoersbewijs', 'Hun telefoon'], a: 1 },
    ],
  },
  {
    id: 'a2l02',
    type: 'omroep',
    script: `Beste klanten, welkom bij supermarkt De Molen. Deze week hebben wij een speciale aanbieding: alle soorten kaas voor de halve prijs. U vindt de kaas achterin de winkel, bij de koeling. Verder is er vandaag een klein kind gevonden bij de ingang. De ouders kunnen zich melden bij de servicebalie. Onze winkel sluit vandaag om acht uur. Wij wensen u veel winkelplezier.`,
    qs: [
      { q: 'Wat is deze week in de aanbieding?', o: ['Kaas', 'Brood', 'Fruit'], a: 0 },
      { q: 'Waar ligt de kaas?', o: ['Bij de ingang', 'Achterin de winkel', 'Bij de kassa'], a: 1 },
      { q: 'Waar moeten de ouders van het kind naartoe?', o: ['Naar de kassa', 'Naar de uitgang', 'Naar de servicebalie'], a: 2 },
      { q: 'Hoe laat sluit de winkel vandaag?', o: ['Om acht uur', 'Om negen uur', 'Om zes uur'], a: 0 },
    ],
  },
  {
    id: 'a2l03',
    type: 'omroep',
    script: `Goedemiddag, beste bezoekers van zwembad De Golf. Over vijftien minuten sluit het buitenbad, omdat er onweer aankomt. U kunt binnen blijven zwemmen in het grote bad. Het kinderbad blijft ook open. Wilt u uw handdoeken en tassen niet op de rand van het bad leggen? Gebruik hiervoor de kluisjes bij de kleedkamers. Een kluisje kost vijftig cent. Vanavond is het zwembad open tot negen uur. Tot ziens en veel plezier.`,
    qs: [
      { q: 'Waarom sluit het buitenbad?', o: ['Er komt onweer aan', 'Het is te druk', 'Het water is te koud'], a: 0 },
      { q: 'Wanneer sluit het buitenbad?', o: ['Over vijf minuten', 'Over vijftien minuten', 'Over een uur'], a: 1 },
      { q: 'Waar moeten bezoekers hun tassen bewaren?', o: ['Op de rand van het bad', 'Bij de ingang', 'In de kluisjes'], a: 2 },
      { q: 'Hoeveel kost een kluisje?', o: ['Vijftig cent', 'Een euro', 'Twee euro'], a: 0 },
      { q: 'Tot hoe laat is het zwembad vanavond open?', o: ['Tot acht uur', 'Tot negen uur', 'Tot tien uur'], a: 1 },
    ],
  },
  {
    id: 'a2l04',
    type: 'omroep',
    script: `Beste leerlingen, dit is een bericht van de administratie. Morgen beginnen de lessen een uur later, om negen uur, omdat de docenten een vergadering hebben. De schoolbus rijdt daarom ook later. Vergeet niet: vrijdag is er een sportdag in het park. Trek makkelijke kleren aan en neem een lunchpakket mee, want de kantine is die dag gesloten. Leerlingen die niet kunnen komen, moeten dat vandaag melden bij meneer Jansen in lokaal twaalf.`,
    qs: [
      { q: 'Waarom beginnen de lessen morgen later?', o: ['De schoolbus is kapot', 'De docenten hebben een vergadering', 'Het is te warm in de lokalen'], a: 1 },
      { q: 'Hoe laat beginnen de lessen morgen?', o: ['Om acht uur', 'Om tien uur', 'Om negen uur'], a: 2 },
      { q: 'Wat moeten leerlingen vrijdag meenemen?', o: ['Een lunchpakket', 'Hun boeken', 'Geld voor de kantine'], a: 0 },
      { q: 'Bij wie melden leerlingen zich af voor de sportdag?', o: ['Bij de directeur', 'Bij meneer Jansen', 'Bij de administratie'], a: 1 },
    ],
  },
  {
    id: 'a2l05',
    type: 'omroep',
    script: `Goedenavond, beste bezoekers. De bibliotheek sluit over een half uur, om negen uur. Wilt u nog boeken lenen? Kom dan nu naar de automaten bij de uitgang. Boeken terugbrengen kan altijd, ook als wij gesloten zijn: gebruik de brievenbus naast de hoofdingang. Denk eraan: volgende week dinsdag zijn wij de hele dag dicht vanwege een feestdag. Op onze website vindt u alle openingstijden. Bedankt voor uw bezoek en tot ziens.`,
    qs: [
      { q: 'Hoe laat sluit de bibliotheek?', o: ['Om half negen', 'Om negen uur', 'Om tien uur'], a: 1 },
      { q: 'Waar kun je boeken terugbrengen als de bibliotheek dicht is?', o: ['In de brievenbus naast de hoofdingang', 'Bij de automaten', 'Bij de balie'], a: 0 },
      { q: 'Waarom is de bibliotheek dinsdag dicht?', o: ['Er is een verbouwing', 'Het personeel vergadert', 'Het is een feestdag'], a: 2 },
      { q: 'Waar vind je de openingstijden?', o: ['Op de website', 'Op een poster', 'In de krant'], a: 0 },
    ],
  },
  {
    id: 'a2l06',
    type: 'omroep',
    script: `Welkom in het gemeentehuis van Rijnstad. Heeft u een afspraak voor een paspoort of rijbewijs? Meld u dan eerst aan bij de zuil in de hal. U krijgt een nummer en dat nummer ziet u straks op het scherm. Zonder afspraak kunnen wij u vandaag helaas niet helpen. Een nieuwe afspraak maakt u via onze website of telefonisch. Let op: de lift is vandaag buiten gebruik. De trap vindt u links naast de balie.`,
    qs: [
      { q: 'Wat moet je eerst doen als je een afspraak hebt?', o: ['Wachten bij de balie', 'Je aanmelden bij de zuil in de hal', 'Meteen naar boven lopen'], a: 1 },
      { q: 'Wat gebeurt er als je geen afspraak hebt?', o: ['Je wordt vandaag niet geholpen', 'Je krijgt een nummer', 'Je moet even wachten'], a: 0 },
      { q: 'Wat is er vandaag buiten gebruik?', o: ['De zuil', 'Het scherm', 'De lift'], a: 2 },
      { q: 'Waar is de trap?', o: ['Rechts naast de ingang', 'Links naast de balie', 'Achter het scherm'], a: 1 },
    ],
  },
  {
    id: 'a2l07',
    type: 'omroep',
    script: `Beste bezoekers van winkelcentrum De Passage. Zaterdag vieren wij ons twintigjarig bestaan. Er is dan muziek in de grote hal en voor de kinderen komt er een clown. Bij de bakker krijgt u die dag bij tien euro aan boodschappen een gratis brood. Het winkelcentrum is zaterdag extra lang open, tot zeven uur. Parkeren is het hele weekend gratis in de garage onder het winkelcentrum. Wij hopen u zaterdag te zien.`,
    qs: [
      { q: 'Wat viert het winkelcentrum zaterdag?', o: ['Zijn twintigjarig bestaan', 'De opening van een nieuwe winkel', 'Het nieuwe jaar'], a: 0 },
      { q: 'Wat is er zaterdag voor de kinderen?', o: ['Een speeltuin', 'Een clown', 'Een film'], a: 1 },
      { q: 'Wat krijg je bij de bakker bij tien euro aan boodschappen?', o: ['Een gratis taart', 'Korting op koekjes', 'Een gratis brood'], a: 2 },
      { q: 'Tot hoe laat is het winkelcentrum zaterdag open?', o: ['Tot zeven uur', 'Tot zes uur', 'Tot negen uur'], a: 0 },
      { q: 'Waar kun je dit weekend gratis parkeren?', o: ['Op straat', 'In de garage onder het winkelcentrum', 'Naast de bakker'], a: 1 },
    ],
  },
  {
    id: 'a2l08',
    type: 'omroep',
    script: `Dames en heren, welkom in het Natuurmuseum. Om twee uur begint een rondleiding over dieren in de winter. De rondleiding start in de grote zaal op de eerste verdieping en duurt drie kwartier. Deelname is gratis, maar er is plaats voor twintig personen. Haal daarom eerst een kaartje bij de informatiebalie. In het museumcafé op de begane grond kunt u koffie en thee kopen. Eten en drinken is in de zalen niet toegestaan.`,
    qs: [
      { q: 'Waar begint de rondleiding?', o: ['In het museumcafé', 'Bij de ingang', 'In de grote zaal op de eerste verdieping'], a: 2 },
      { q: 'Hoe lang duurt de rondleiding?', o: ['Drie kwartier', 'Een uur', 'Een half uur'], a: 0 },
      { q: 'Wat moet je doen om mee te doen met de rondleiding?', o: ['Je online aanmelden', 'Een kaartje halen bij de informatiebalie', 'Betalen in het café'], a: 1 },
      { q: 'Wat mag niet in de zalen?', o: ['Foto’s maken', 'Praten', 'Eten en drinken'], a: 2 },
    ],
  },
  {
    id: 'a2l09',
    type: 'voicemail',
    script: `Goedemorgen, u spreekt met Sandra, de assistente van huisarts De Wit. Ik bel voor mevrouw Yilmaz. U heeft morgen om tien uur een afspraak, maar de dokter is morgen ziek. De afspraak kan daarom niet doorgaan. Ik heb een nieuwe afspraak voor u gemaakt: donderdag om kwart over negen. Kunt u niet op donderdag? Bel ons dan terug op werkdagen tussen acht en twaalf uur. Fijne dag verder.`,
    qs: [
      { q: 'Wie spreekt dit bericht in?', o: ['De huisarts zelf', 'De assistente van de huisarts', 'Een medewerker van de apotheek'], a: 1 },
      { q: 'Waarom kan de afspraak van morgen niet doorgaan?', o: ['De dokter is ziek', 'Mevrouw Yilmaz is te laat', 'De praktijk is dicht'], a: 0 },
      { q: 'Wanneer is de nieuwe afspraak?', o: ['Morgen om tien uur', 'Donderdag om tien uur', 'Donderdag om kwart over negen'], a: 2 },
      { q: 'Wanneer kan mevrouw Yilmaz terugbellen?', o: ['Op werkdagen tussen acht en twaalf uur', 'Elke middag na twaalf uur', 'Alleen op donderdag'], a: 0 },
    ],
  },
  {
    id: 'a2l10',
    type: 'voicemail',
    script: `Goedemiddag, dit is Peter van garage Van Dam. Ik bel over uw auto. We hebben het probleem gevonden: de accu is kapot. Een nieuwe accu kost honderdtwintig euro, en met het werkloon erbij bent u ongeveer honderdvijftig euro kwijt. Als u akkoord bent, is de auto morgen aan het eind van de middag klaar. Wilt u mij even terugbellen om dit door te geven? U kunt de auto ophalen tot zes uur. Tot horens.`,
    qs: [
      { q: 'Wat is er kapot aan de auto?', o: ['De motor', 'De accu', 'De remmen'], a: 1 },
      { q: 'Hoeveel kost de reparatie in totaal ongeveer?', o: ['Honderdtwintig euro', 'Honderd euro', 'Honderdvijftig euro'], a: 2 },
      { q: 'Wat moet de klant nu doen?', o: ['De garage terugbellen', 'Meteen langskomen', 'Een e-mail sturen'], a: 0 },
      { q: 'Wanneer is de auto klaar?', o: ['Morgen aan het eind van de middag', 'Vandaag om zes uur', 'Volgende week'], a: 0 },
    ],
  },
  {
    id: 'a2l11',
    type: 'voicemail',
    script: `Hallo, met Fatima van kapsalon Knip. Dit bericht is voor meneer De Boer. U heeft zaterdag om elf uur een afspraak voor knippen. Helaas moet ik de afspraak verzetten, want onze salon wordt zaterdagochtend geverfd. Kunt u in de middag komen, om twee uur? Als dat niet lukt, kan het ook maandag om tien uur. Laat u het even weten met een belletje of een berichtje? Ons nummer staat op de website. Bedankt en tot ziens.`,
    qs: [
      { q: 'Waarom wordt de afspraak verzet?', o: ['De kapper is ziek', 'De salon wordt die ochtend geverfd', 'Het is te druk in de salon'], a: 1 },
      { q: 'Hoe laat was de afspraak eerst?', o: ['Om elf uur', 'Om twee uur', 'Om tien uur'], a: 0 },
      { q: 'Wat is het nieuwe voorstel voor zaterdag?', o: ['Om tien uur ’s ochtends', 'Om twee uur ’s middags', 'Om vier uur ’s middags'], a: 1 },
      { q: 'Hoe kan meneer De Boer reageren?', o: ['Alleen per e-mail', 'Langsgaan bij de salon', 'Bellen of een berichtje sturen'], a: 2 },
    ],
  },
  {
    id: 'a2l12',
    type: 'voicemail',
    script: `Goedemorgen, u spreekt met juf Annemiek van basisschool De Regenboog. Ik bel over uw zoon Bilal. Hij is vanochtend gevallen op het schoolplein en heeft pijn aan zijn pols. Het gaat nu redelijk goed, hij zit gewoon in de klas. Maar wij denken dat een dokter er even naar moet kijken. Kunt u hem vandaag eerder ophalen? De school is normaal om drie uur uit. Belt u mij gerust terug op het nummer van school.`,
    qs: [
      { q: 'Wie belt er?', o: ['De directeur van de school', 'De juf van Bilal', 'De schoolarts'], a: 1 },
      { q: 'Wat is er gebeurd?', o: ['Bilal is gevallen op het schoolplein', 'Bilal is ziek naar huis gegaan', 'Bilal heeft een toets gemist'], a: 0 },
      { q: 'Waar heeft Bilal pijn?', o: ['Aan zijn been', 'Aan zijn hoofd', 'Aan zijn pols'], a: 2 },
      { q: 'Wat vraagt de juf aan de ouder?', o: ['Bilal vandaag eerder ophalen', 'Medicijnen naar school brengen', 'Naar school komen voor een gesprek'], a: 0 },
    ],
  },
  {
    id: 'a2l13',
    type: 'voicemail',
    script: `Dag Amir, je spreekt met Karin van restaurant De Zon. Ik bel over je rooster van volgende week. Kun jij woensdagavond werken in plaats van dinsdagavond? Je collega Tom is dan vrij, want hij moet naar een bruiloft. Je dienst begint gewoon om vijf uur en duurt tot elf uur. O ja, neem woensdag je zwarte schoenen mee, want er komt een grote groep gasten. Bel of app me even of het lukt. Groetjes!`,
    qs: [
      { q: 'Waarover gaat dit bericht?', o: ['Het rooster van volgende week', 'Een nieuw contract', 'Het salaris van Amir'], a: 0 },
      { q: 'Waarom kan Tom woensdag niet werken?', o: ['Hij is ziek', 'Hij moet naar een bruiloft', 'Hij heeft vakantie'], a: 1 },
      { q: 'Hoe laat begint de dienst?', o: ['Om elf uur', 'Om zes uur', 'Om vijf uur'], a: 2 },
      { q: 'Wat moet Amir woensdag meenemen?', o: ['Zijn zwarte schoenen', 'Een wit overhemd', 'Zijn contract'], a: 0 },
    ],
  },
  {
    id: 'a2l14',
    type: 'voicemail',
    script: `Goedemiddag, u spreekt met de praktijk van tandarts Mulder. Dit is een bericht voor mevrouw Petrova. Het is weer tijd voor uw halfjaarlijkse controle. U kunt zelf een afspraak maken via onze website, of u belt ons op dinsdag of donderdag tussen negen en vier uur. Komt u met de auto? Let dan op: voor onze deur wordt de straat opengebroken. U kunt parkeren in de Molenstraat, dat is twee minuten lopen. Tot binnenkort.`,
    qs: [
      { q: 'Waarom belt de praktijk?', o: ['Er moet een kies getrokken worden', 'Het is tijd voor de controle', 'Er is een rekening niet betaald'], a: 1 },
      { q: 'Op welke dagen kun je de praktijk bellen?', o: ['Dinsdag en donderdag', 'Maandag en vrijdag', 'Elke werkdag'], a: 0 },
      { q: 'Waarom kun je niet voor de deur parkeren?', o: ['Het is er te druk', 'Parkeren is er te duur', 'De straat wordt opengebroken'], a: 2 },
      { q: 'Waar kun je wel parkeren?', o: ['In de Molenstraat', 'Achter de praktijk', 'Bij het station'], a: 0 },
    ],
  },
  {
    id: 'a2l15',
    type: 'voicemail',
    script: `Goedemorgen, dit is een bericht van apotheek Centrum voor meneer Haddad. Uw medicijnen liggen voor u klaar. U kunt ze vandaag nog ophalen tot half zes. Lukt dat niet, dan kunt u ook morgen komen. Neemt u uw legitimatiebewijs mee, want dit is de eerste keer dat u deze medicijnen haalt. Heeft u vragen over het gebruik? Onze apotheker legt het u graag uit aan de balie. Tot straks.`,
    qs: [
      { q: 'Waarom belt de apotheek?', o: ['Er staat nog een rekening open', 'De medicijnen liggen klaar', 'De apotheek gaat verhuizen'], a: 1 },
      { q: 'Tot hoe laat kan meneer Haddad vandaag komen?', o: ['Tot vijf uur', 'Tot zes uur', 'Tot half zes'], a: 2 },
      { q: 'Wat moet hij meenemen?', o: ['Zijn legitimatiebewijs', 'Zijn bankpas', 'Het oude doosje'], a: 0 },
      { q: 'Wie kan uitleg geven over de medicijnen?', o: ['De huisarts', 'De apotheker', 'De assistente van de dokter'], a: 1 },
    ],
  },
  {
    id: 'a2l16',
    type: 'voicemail',
    script: `Goedendag, u spreekt met de bibliotheek van Westdorp. Dit bericht is voor mevrouw Chen. Het boek dat u heeft gereserveerd, is binnen. Het ligt twee weken voor u klaar bij de balie. Daarna gaat het naar de volgende lezer. Wij zijn maandag gesloten, maar de rest van de week open van tien tot acht. Denkt u ook aan de twee boeken die u nog thuis heeft? Die moeten uiterlijk vrijdag terug. Tot ziens.`,
    qs: [
      { q: 'Waarom belt de bibliotheek?', o: ['Het gereserveerde boek is binnen', 'Mevrouw Chen moet een boete betalen', 'De bibliotheek gaat sluiten'], a: 0 },
      { q: 'Hoe lang blijft het boek voor haar klaarliggen?', o: ['Eén week', 'Twee weken', 'Eén maand'], a: 1 },
      { q: 'Op welke dag is de bibliotheek gesloten?', o: ['Vrijdag', 'Zondag', 'Maandag'], a: 2 },
      { q: 'Wat moet er uiterlijk vrijdag gebeuren?', o: ['Twee boeken terugbrengen', 'Het nieuwe boek ophalen', 'De bibliotheekpas verlengen'], a: 0 },
    ],
  },
  {
    id: 'a2l17',
    type: 'gesprek',
    script: `Medewerker: Goedemorgen, waarmee kan ik u helpen? Mevrouw Osman: Goedemorgen. Ik kom mijn nieuwe paspoort ophalen. Medewerker: Dat kan. Heeft u de brief bij u en uw oude paspoort? Mevrouw Osman: De brief wel, maar mijn oude paspoort ligt nog thuis. Medewerker: Dan mag ik het nieuwe paspoort helaas niet meegeven. Het oude moet ik hier ongeldig maken. Mevrouw Osman: Wat vervelend. Tot hoe laat bent u open? Medewerker: Tot vijf uur vanmiddag. U kunt vandaag gewoon nog terugkomen, dat kost geen extra geld. Mevrouw Osman: Dan haal ik het thuis op. Tot straks.`,
    qs: [
      { q: 'Waarom is mevrouw Osman bij het gemeentehuis?', o: ['Om haar nieuwe paspoort op te halen', 'Om een rijbewijs aan te vragen', 'Om een verhuizing door te geven'], a: 0 },
      { q: 'Wat is zij vergeten mee te nemen?', o: ['De brief', 'Haar oude paspoort', 'Haar bankpas'], a: 1 },
      { q: 'Waarom heeft de medewerker het oude paspoort nodig?', o: ['Om het ongeldig te maken', 'Om de foto te controleren', 'Om het adres te controleren'], a: 0 },
      { q: 'Wat gaat mevrouw Osman nu doen?', o: ['Morgen terugkomen', 'Een nieuwe afspraak maken', 'Het oude paspoort thuis ophalen'], a: 2 },
      { q: 'Tot hoe laat is het gemeentehuis open?', o: ['Tot vier uur', 'Tot vijf uur', 'Tot zes uur'], a: 1 },
    ],
  },
  {
    id: 'a2l18',
    type: 'gesprek',
    script: `Verkoper: Goedemorgen! Zegt u het maar. Meneer Silva: Een bruin brood, alstublieft. Gesneden graag. Verkoper: Natuurlijk. Anders nog iets? De croissants zijn vandaag in de aanbieding: vier voor twee euro. Meneer Silva: Lekker, doe maar vier. Hoeveel is het samen? Verkoper: Het brood is twee euro tachtig, dus samen vier euro tachtig. Meneer Silva: Kan ik pinnen? Verkoper: Jazeker, pinnen mag altijd. Wilt u er een tasje bij? Dat kost tien cent. Meneer Silva: Nee, dank u. Ik heb zelf een tas bij me.`,
    qs: [
      { q: 'Waar vindt dit gesprek plaats?', o: ['Bij de bakker', 'In de supermarkt', 'Op de markt'], a: 0 },
      { q: 'Wat is vandaag in de aanbieding?', o: ['Bruin brood', 'Croissants', 'Taart'], a: 1 },
      { q: 'Hoeveel betaalt meneer Silva in totaal?', o: ['Twee euro tachtig', 'Twee euro', 'Vier euro tachtig'], a: 2 },
      { q: 'Hoe betaalt hij?', o: ['Contant', 'Met pin', 'Met een tegoedbon'], a: 1 },
      { q: 'Waarom wil hij geen tasje?', o: ['Hij heeft zelf een tas bij zich', 'Hij vindt het te duur', 'Hij draagt het brood zo mee'], a: 0 },
    ],
  },
  {
    id: 'a2l19',
    type: 'gesprek',
    script: `Buurvrouw: Hallo Amina, heb je even? Amina: Ja hoor, wat is er? Buurvrouw: Wij gaan volgende week op vakantie, tien dagen naar Spanje. Wil jij misschien onze planten water geven? Amina: Natuurlijk, dat is geen probleem. Moet ik ook de post uit de brievenbus halen? Buurvrouw: Graag! De sleutel breng ik zondagavond even langs. O, en de planten in de keuken hebben maar één keer per week water nodig. Amina: Prima. Fijne vakantie alvast! Buurvrouw: Dank je wel. Als dank nemen we iets lekkers voor je mee.`,
    qs: [
      { q: 'Wat vraagt de buurvrouw aan Amina?', o: ['Op de kat passen', 'De planten water geven', 'Het gras maaien'], a: 1 },
      { q: 'Hoe lang gaat de buurvrouw op vakantie?', o: ['Tien dagen', 'Een week', 'Twee weken'], a: 0 },
      { q: 'Wanneer krijgt Amina de sleutel?', o: ['Vrijdagochtend', 'Maandag', 'Zondagavond'], a: 2 },
      { q: 'Hoe vaak hebben de keukenplanten water nodig?', o: ['Elke dag', 'Eén keer per week', 'Twee keer per week'], a: 1 },
    ],
  },
  {
    id: 'a2l20',
    type: 'gesprek',
    script: `Joris: Hé Selma, weet jij hoe het kopieerapparaat werkt? Selma: Ja hoor. Wat wil je doen? Joris: Ik moet dertig kopieën maken voor de vergadering van drie uur. Selma: Kijk, je legt het papier hier neer en kiest het aantal op het scherm. Maar het apparaat op onze verdieping is kapot. Ga maar naar de tweede verdieping, naast de keuken staat er nog een. Joris: Ah, dank je. Doe jij ook mee met de vergadering? Selma: Nee, ik heb om drie uur een afspraak met een klant. Jullie horen morgen van mij hoe het ging.`,
    qs: [
      { q: 'Wat wil Joris doen?', o: ['Kopieën maken', 'Koffie zetten', 'Een klant bellen'], a: 0 },
      { q: 'Wat is het probleem?', o: ['Het papier is op', 'Het apparaat op hun verdieping is kapot', 'Joris heeft geen toegangspas'], a: 1 },
      { q: 'Waar staat het andere kopieerapparaat?', o: ['Op de tweede verdieping, naast de keuken', 'Bij de ingang', 'In de vergaderzaal'], a: 0 },
      { q: 'Waarom komt Selma niet naar de vergadering?', o: ['Ze is vrij', 'Ze is ziek', 'Ze heeft een afspraak met een klant'], a: 2 },
      { q: 'Hoe laat is de vergadering?', o: ['Om twee uur', 'Om drie uur', 'Om vier uur'], a: 1 },
    ],
  },
  {
    id: 'a2l21',
    type: 'gesprek',
    script: `Marktkoopman: Goedemorgen mevrouw! Verse aardbeien, twee bakjes voor drie euro. Mevrouw Novak: Zijn ze zoet? Marktkoopman: Heel zoet, proef maar. Ze komen vandaag vers van de boer. Mevrouw Novak: Mmm, lekker. Doe maar twee bakjes. En een kilo appels graag. Marktkoopman: De appels kosten twee euro per kilo. Samen is dat vijf euro. Mevrouw Novak: Alstublieft. Bent u er volgende week weer? Marktkoopman: Nee, volgende week staan we er niet. Dan is de markt afgelast vanwege het stadsfeest. De week daarna staan we er gewoon weer, op woensdag.`,
    qs: [
      { q: 'Waar vindt dit gesprek plaats?', o: ['Op de markt', 'In de supermarkt', 'In een restaurant'], a: 0 },
      { q: 'Hoeveel kosten twee bakjes aardbeien?', o: ['Twee euro', 'Drie euro', 'Vijf euro'], a: 1 },
      { q: 'Hoeveel betaalt mevrouw Novak in totaal?', o: ['Drie euro', 'Vier euro', 'Vijf euro'], a: 2 },
      { q: 'Waarom is er volgende week geen markt?', o: ['Vanwege het stadsfeest', 'Vanwege slecht weer', 'De koopman is op vakantie'], a: 0 },
    ],
  },
  {
    id: 'a2l22',
    type: 'gesprek',
    script: `Verkoopster: Goedemiddag, kan ik u helpen? Meneer Popescu: Ja, ik heb deze broek vorige week gekocht, maar hij is te klein. Kan ik hem ruilen? Verkoopster: Heeft u de bon nog? Meneer Popescu: Ja, hier is hij. Verkoopster: Prima. Welke maat zoekt u? Meneer Popescu: Maat achtenveertig, denk ik. Verkoopster: Even kijken. Deze kleur hebben we niet meer in die maat, maar wel in donkerblauw. Meneer Popescu: Mag ik die even passen? Verkoopster: Natuurlijk. De paskamers zijn achterin de winkel, naast de spiegels.`,
    qs: [
      { q: 'Waarom is meneer Popescu in de winkel?', o: ['Hij wil een broek ruilen', 'Hij zoekt een cadeau', 'Hij wil zijn geld terug'], a: 0 },
      { q: 'Wat is het probleem met de broek?', o: ['Hij is kapot', 'Hij is te klein', 'De kleur is verkeerd'], a: 1 },
      { q: 'Wat moet meneer Popescu laten zien?', o: ['Zijn bankpas', 'Zijn legitimatie', 'De bon'], a: 2 },
      { q: 'Welke kleur is er nog wel in zijn maat?', o: ['Donkerblauw', 'Zwart', 'Grijs'], a: 0 },
      { q: 'Waar zijn de paskamers?', o: ['Bij de ingang', 'Achterin de winkel, naast de spiegels', 'Op de eerste verdieping'], a: 1 },
    ],
  },
  {
    id: 'a2l23',
    type: 'gesprek',
    script: `Fietsenmaker: Goedemorgen! Wat kan ik voor u doen? Mevrouw Sato: Mijn achterband is lek. Kunt u hem plakken? Fietsenmaker: Even kijken. Hm, de band is erg oud. Plakken kan, maar een nieuwe band is beter. Die kost achttien euro. Met plakken bent u acht euro kwijt. Mevrouw Sato: Doe dan maar een nieuwe band. Wanneer is de fiets klaar? Fietsenmaker: Het is druk vandaag. Rond vier uur, is dat goed? Mevrouw Sato: Prima. Mijn licht doet het ook niet. Kunt u daar ook naar kijken? Fietsenmaker: Doe ik. Tot vanmiddag.`,
    qs: [
      { q: 'Wat is er met de fiets?', o: ['De achterband is lek', 'De ketting is kapot', 'De rem doet het niet'], a: 0 },
      { q: 'Wat raadt de fietsenmaker aan?', o: ['De band plakken', 'Een nieuwe band', 'Een nieuwe fiets kopen'], a: 1 },
      { q: 'Hoeveel kost een nieuwe band?', o: ['Acht euro', 'Tien euro', 'Achttien euro'], a: 2 },
      { q: 'Hoe laat is de fiets ongeveer klaar?', o: ['Rond twaalf uur', 'Rond vier uur', 'Morgenochtend'], a: 1 },
      { q: 'Waar moet de fietsenmaker ook naar kijken?', o: ['Het licht', 'Het zadel', 'De bel'], a: 0 },
    ],
  },
  {
    id: 'a2l24',
    type: 'gesprek',
    script: `Medewerker: Goedenavond, welkom bij sportclub Vitaal. Meneer Traore: Goedenavond. Ik wil graag lid worden. Wat kost dat? Medewerker: Een abonnement kost vijfentwintig euro per maand. Dan mag u elke dag komen sporten. Meneer Traore: Zijn er ook lessen? Medewerker: Ja, de groepslessen zitten bij de prijs in. Het rooster hangt bij de kleedkamers. Meneer Traore: Kan ik eerst een keer proberen? Medewerker: Zeker, de eerste les is gratis. Vult u dit formulier even in? Vergeet uw handtekening niet, onderaan. Meneer Traore: Alstublieft. Medewerker: Mooi, dan kunt u vanavond meteen meedoen.`,
    qs: [
      { q: 'Wat wil meneer Traore?', o: ['Zijn abonnement stoppen', 'Een les afzeggen', 'Lid worden van de sportclub'], a: 2 },
      { q: 'Hoeveel kost een abonnement per maand?', o: ['Vijftien euro', 'Vijfentwintig euro', 'Vijfendertig euro'], a: 1 },
      { q: 'Wat kost de eerste les?', o: ['Niets', 'Vijf euro', 'De helft van de prijs'], a: 0 },
      { q: 'Waar hangt het lesrooster?', o: ['Bij de ingang', 'Achter de balie', 'Bij de kleedkamers'], a: 2 },
      { q: 'Wat mag hij niet vergeten op het formulier?', o: ['Zijn handtekening', 'Zijn telefoonnummer', 'Zijn e-mailadres'], a: 0 },
    ],
  },
  {
    id: 'a2l25',
    type: 'gesprek',
    script: `Medewerker: Goedemiddag. Mevrouw Ivanova: Goedemiddag, ik kom een pakket ophalen. Hier is het bericht op mijn telefoon. Medewerker: Dank u. Mag ik ook uw legitimatie zien? Mevrouw Ivanova: Natuurlijk, alstublieft. Medewerker: Even zoeken. Het is een groot pakket, het staat achter. Momentje. Alstublieft. Wilt u hier tekenen op het scherm? Mevrouw Ivanova: Zo. O, het is best zwaar. Medewerker: Zal ik het naar uw auto dragen? Mevrouw Ivanova: Nee, dank u. Ik ben met de fiets, het lukt wel. Fijne dag nog!`,
    qs: [
      { q: 'Wat komt mevrouw Ivanova doen?', o: ['Een pakket versturen', 'Een pakket ophalen', 'Een brief posten'], a: 1 },
      { q: 'Wat moet zij laten zien, behalve het bericht?', o: ['Haar legitimatie', 'Haar bankpas', 'Haar adres'], a: 0 },
      { q: 'Waar moet zij tekenen?', o: ['Op een papier', 'Op de doos', 'Op het scherm'], a: 2 },
      { q: 'Hoe is mevrouw Ivanova gekomen?', o: ['Met de fiets', 'Met de auto', 'Lopend'], a: 0 },
    ],
  },
  {
    id: 'a2l26',
    type: 'gesprek',
    script: `Nadia: Hoi Lin, kom je zaterdag naar mijn verjaardagsfeest? Lin: Gezellig! Hoe laat begint het? Nadia: Om acht uur, bij mij thuis. Neem je iets te drinken mee? Voor eten zorg ik zelf, ik maak soep en hapjes. Lin: Prima, ik neem sap en cola mee. Kan ik nog iemand meenemen? Mijn zus logeert dit weekend bij mij. Nadia: Natuurlijk, hoe meer mensen, hoe leuker. O, en kom met de bus, want parkeren is moeilijk in mijn straat. Lin: Goed idee. Tot zaterdag!`,
    qs: [
      { q: 'Wat is er zaterdag?', o: ['Een verjaardagsfeest', 'Een bruiloft', 'Een etentje in een restaurant'], a: 0 },
      { q: 'Wat neemt Lin mee?', o: ['Hapjes', 'Iets te drinken', 'Een taart'], a: 1 },
      { q: 'Wie wil Lin meenemen naar het feest?', o: ['Haar buurvrouw', 'Een collega', 'Haar zus'], a: 2 },
      { q: 'Waarom kan Lin beter met de bus komen?', o: ['De straat is afgesloten', 'Parkeren is moeilijk in de straat', 'Nadia woont ver weg'], a: 1 },
      { q: 'Hoe laat begint het feest?', o: ['Om zeven uur', 'Om negen uur', 'Om acht uur'], a: 2 },
    ],
  },
  {
    id: 'a2l27',
    type: 'telefoon',
    script: `Assistente: Praktijk voor fysiotherapie Beweeg, goedemorgen. Meneer Kovac: Goedemorgen, ik wil graag een afspraak maken. Ik heb last van mijn rug. Assistente: Dat kan. Bent u al eerder bij ons geweest? Meneer Kovac: Nee, dit is de eerste keer. Assistente: Dan plannen we wat extra tijd in. Kunt u woensdag om half elf? Meneer Kovac: Woensdag werk ik. Kan het ook in de avond? Assistente: Even kijken. Donderdag om zes uur? Meneer Kovac: Ja, dat is goed. Assistente: Neemt u uw verzekeringspas mee? Tot donderdag.`,
    qs: [
      { q: 'Waarom belt meneer Kovac?', o: ['Hij wil een afspraak maken', 'Hij wil een afspraak afzeggen', 'Hij wil een rekening betalen'], a: 0 },
      { q: 'Waar heeft hij last van?', o: ['Zijn knie', 'Zijn rug', 'Zijn schouder'], a: 1 },
      { q: 'Waarom kan hij woensdag niet?', o: ['Hij moet dan werken', 'Hij is dan op vakantie', 'Hij heeft dan al een afspraak'], a: 0 },
      { q: 'Wanneer is de afspraak?', o: ['Woensdag om half elf', 'Donderdag om vijf uur', 'Donderdag om zes uur'], a: 2 },
      { q: 'Wat moet hij meenemen?', o: ['Zijn verzekeringspas', 'Zijn medicijnen', 'Een handdoek'], a: 0 },
    ],
  },
  {
    id: 'a2l28',
    type: 'telefoon',
    script: `Medewerker: Pizzeria Roma, goedenavond. Mevrouw Berg: Goedenavond, ik wil graag twee pizza’s bestellen. Eén margherita en één met salami. Medewerker: Komt u de pizza’s ophalen, of moeten wij bezorgen? Mevrouw Berg: Bezorgen graag, Lindestraat veertien. Medewerker: Dat is samen negentien euro vijftig. Met de bezorgkosten erbij eenentwintig euro vijftig. Mevrouw Berg: Hoe lang duurt het? Medewerker: Ongeveer drie kwartier, het is druk vanavond. Mevrouw Berg: Dat is goed. Kan ik bij de bezorger pinnen? Medewerker: Ja hoor, onze bezorgers hebben een pinapparaat bij zich. Tot straks!`,
    qs: [
      { q: 'Wat bestelt mevrouw Berg?', o: ['Twee pizza’s', 'Eén pizza en een salade', 'Drie pizza’s'], a: 0 },
      { q: 'Hoeveel betaalt zij in totaal?', o: ['Negentien euro vijftig', 'Eenentwintig euro vijftig', 'Vijfentwintig euro'], a: 1 },
      { q: 'Hoe lang duurt de bezorging ongeveer?', o: ['Een kwartier', 'Een half uur', 'Drie kwartier'], a: 2 },
      { q: 'Waarom duurt het zo lang?', o: ['Het is druk vanavond', 'De bezorger is ziek', 'De oven is kapot'], a: 0 },
      { q: 'Hoe gaat mevrouw Berg betalen?', o: ['Contant aan de deur', 'Met pin bij de bezorger', 'Vooraf via internet'], a: 1 },
    ],
  },
  {
    id: 'a2l29',
    type: 'telefoon',
    script: `Medewerker: Klantenservice SnelNet, u spreekt met Dennis. Meneer Ali: Goedemiddag, mijn internet doet het niet sinds vanochtend. Medewerker: Wat vervelend. Ik kijk even voor u. Er is een storing in uw wijk, onze monteurs zijn al bezig. Meneer Ali: Hoe lang gaat dat duren? Medewerker: Wij verwachten dat het vanavond om acht uur is opgelost. Meneer Ali: Ik werk thuis, kan het niet sneller? Medewerker: Helaas niet. Maar u krijgt automatisch geld terug voor deze dag. U hoeft daarvoor niets te doen. Meneer Ali: Oké, dank u wel. Medewerker: Graag gedaan, nog een fijne dag.`,
    qs: [
      { q: 'Waarom belt meneer Ali?', o: ['Zijn internet doet het niet', 'Zijn televisie is kapot', 'Hij wil een nieuw abonnement'], a: 0 },
      { q: 'Wat is de oorzaak van het probleem?', o: ['Een kapotte kabel in huis', 'Een storing in de wijk', 'Een rekening die niet is betaald'], a: 1 },
      { q: 'Wanneer is de storing waarschijnlijk opgelost?', o: ['Vanavond om acht uur', 'Morgenochtend', 'Over een uur'], a: 0 },
      { q: 'Wat moet meneer Ali doen om geld terug te krijgen?', o: ['Een formulier invullen', 'Opnieuw bellen', 'Niets'], a: 2 },
    ],
  },
  {
    id: 'a2l30',
    type: 'telefoon',
    script: `Medewerker: Zwemschool De Plons, goedemiddag. Mevrouw Diallo: Goedemiddag. Ik bel voor informatie over zwemles voor mijn dochter. Zij is vijf jaar. Medewerker: Vijf jaar is een goede leeftijd om te beginnen. De lessen voor beginners zijn op maandag en op zaterdag. Mevrouw Diallo: Wat kost het? Medewerker: Veertig euro per maand, en u betaalt één keer tien euro inschrijfgeld. Mevrouw Diallo: Is er plaats? Medewerker: Op zaterdag is er een wachtlijst, maar op maandag om vier uur kan uw dochter direct beginnen. Mevrouw Diallo: Dan kies ik maandag. Medewerker: Prima, ik zet haar op de lijst.`,
    qs: [
      { q: 'Waarom belt mevrouw Diallo?', o: ['Ze wil informatie over zwemles', 'Ze wil een les afzeggen', 'Ze wil kaartjes voor het zwembad'], a: 0 },
      { q: 'Hoe oud is haar dochter?', o: ['Vier jaar', 'Vijf jaar', 'Zes jaar'], a: 1 },
      { q: 'Hoeveel is het inschrijfgeld?', o: ['Tien euro', 'Veertig euro', 'Vijftig euro'], a: 0 },
      { q: 'Waarom kiest mevrouw Diallo voor de maandag?', o: ['Maandag is goedkoper', 'Zaterdag past niet in haar agenda', 'Op zaterdag is er een wachtlijst'], a: 2 },
      { q: 'Hoe laat is de les op maandag?', o: ['Om drie uur', 'Om vier uur', 'Om vijf uur'], a: 1 },
    ],
  },
  {
    id: 'a2l31',
    type: 'telefoon',
    script: `Centrale: Taxicentrale Stad, goedenavond. Meneer Janssen: Goedenavond, ik wil graag een taxi bestellen voor morgenochtend. Centrale: Waar en hoe laat? Meneer Janssen: Om zes uur, bij de Kerkstraat drie. Ik moet naar het vliegveld. Centrale: Dat kan. Met hoeveel personen reist u? Meneer Janssen: Met twee personen, en we hebben twee grote koffers. Centrale: Dan stuur ik een grote auto. De rit kost ongeveer vijfenveertig euro. Meneer Janssen: Prima. Centrale: De chauffeur belt u als hij voor de deur staat. Staat u alstublieft op tijd klaar. Meneer Janssen: Doen we. Bedankt!`,
    qs: [
      { q: 'Waarvoor belt meneer Janssen?', o: ['Om een taxi te bestellen', 'Om een rit af te zeggen', 'Om te vragen waar de taxi blijft'], a: 0 },
      { q: 'Waar gaat hij morgen naartoe?', o: ['Naar het station', 'Naar het vliegveld', 'Naar het ziekenhuis'], a: 1 },
      { q: 'Hoe laat moet de taxi komen?', o: ['Om zes uur ’s ochtends', 'Om zeven uur ’s ochtends', 'Om zes uur ’s avonds'], a: 0 },
      { q: 'Waarom stuurt de centrale een grote auto?', o: ['Er reizen vier personen mee', 'Er zijn twee grote koffers', 'Het regent morgen'], a: 1 },
      { q: 'Wat doet de chauffeur als hij er is?', o: ['Hij belt meneer Janssen', 'Hij toetert', 'Hij wacht tien minuten'], a: 0 },
    ],
  },
  {
    id: 'a2l32',
    type: 'telefoon',
    script: `Medewerker: Woningstichting Goed Wonen, goedemorgen. Mevrouw Rahimi: Goedemorgen, ik bel over mijn verwarming. Het wordt niet warm in huis, en het is zo koud buiten. Medewerker: Wat vervelend. Heeft u gekeken of de druk van de ketel goed is? Mevrouw Rahimi: Ja, mijn buurman heeft gekeken. Hij zegt dat de ketel echt kapot is. Medewerker: Dan stuur ik een monteur. Hij kan vanmiddag tussen één en vier uur komen. Bent u dan thuis? Mevrouw Rahimi: Ja, ik ben thuis. Medewerker: Fijn. De reparatie kost u niets, die betaalt de woningstichting.`,
    qs: [
      { q: 'Waarom belt mevrouw Rahimi?', o: ['Haar verwarming doet het niet', 'Haar kraan lekt', 'Haar huur is te hoog'], a: 0 },
      { q: 'Wie heeft er al naar de ketel gekeken?', o: ['Een monteur', 'Haar buurman', 'Haar man'], a: 1 },
      { q: 'Wanneer komt de monteur?', o: ['Vanmiddag tussen één en vier uur', 'Morgenochtend', 'Vanavond na zes uur'], a: 0 },
      { q: 'Wie betaalt de reparatie?', o: ['Mevrouw Rahimi', 'De monteur', 'De woningstichting'], a: 2 },
    ],
  },
  {
    id: 'a2l33',
    type: 'telefoon',
    script: `Medewerker: Restaurant De Tulp, goedemiddag. Meneer Costa: Goedemiddag, ik wil graag een tafel reserveren voor vrijdagavond. Medewerker: Voor hoeveel personen? Meneer Costa: Voor zes personen, om zeven uur. Medewerker: Even kijken. Om zeven uur zitten we helaas vol. Om half negen hebben we wel plaats. Meneer Costa: Dat is wat laat. En donderdag om zeven uur? Medewerker: Donderdag kan wel. Op welke naam mag ik de reservering zetten? Meneer Costa: Op de naam Costa. O ja, één gast eet geen vlees. Medewerker: Geen probleem, wij hebben ook vegetarische gerechten. Tot donderdag, meneer Costa.`,
    qs: [
      { q: 'Waarvoor belt meneer Costa?', o: ['Om een tafel te reserveren', 'Om eten te bestellen', 'Om een klacht door te geven'], a: 0 },
      { q: 'Waarom lukt vrijdag om zeven uur niet?', o: ['Het restaurant is dan dicht', 'Het restaurant zit dan vol', 'De keuken sluit dan vroeg'], a: 1 },
      { q: 'Wanneer komt hij nu eten?', o: ['Vrijdag om half negen', 'Donderdag om zeven uur', 'Vrijdag om zeven uur'], a: 1 },
      { q: 'Met hoeveel personen komt hij?', o: ['Vier', 'Vijf', 'Zes'], a: 2 },
      { q: 'Wat vertelt hij over één gast?', o: ['Die eet geen vlees', 'Die komt wat later', 'Die zit in een rolstoel'], a: 0 },
    ],
  },
  {
    id: 'a2l34',
    type: 'telefoon',
    script: `Medewerker: Opticien Helder Zicht, goedemiddag. Mevrouw Smit: Goedemiddag. Ik heb morgen een afspraak om mijn nieuwe bril op te halen, maar ik kan niet komen. Mijn moeder is ziek en ik moet haar helpen. Medewerker: Dat geeft niets. Wanneer kunt u wel? Mevrouw Smit: Kan het volgende week dinsdag? Medewerker: Dinsdagochtend om tien uur? Mevrouw Smit: Liever in de middag. Medewerker: Dan noteer ik dinsdag om drie uur. Uw bril blijft hier gewoon liggen. Mevrouw Smit: Fijn, dank u wel. Medewerker: Graag gedaan, en beterschap voor uw moeder.`,
    qs: [
      { q: 'Waarom belt mevrouw Smit?', o: ['Ze wil haar afspraak verzetten', 'Ze wil een nieuwe bril bestellen', 'Haar bril is kapot'], a: 0 },
      { q: 'Waarom kan zij morgen niet komen?', o: ['Ze moet werken', 'Haar moeder is ziek', 'Ze is zelf ziek'], a: 1 },
      { q: 'Wat komt zij doen bij de opticien?', o: ['Haar ogen laten meten', 'Een zonnebril passen', 'Haar nieuwe bril ophalen'], a: 2 },
      { q: 'Wanneer is de nieuwe afspraak?', o: ['Dinsdag om tien uur', 'Dinsdag om drie uur', 'Donderdag om drie uur'], a: 1 },
    ],
  },
  {
    id: 'a2l35',
    type: 'bericht',
    script: `En dan nu het weerbericht. Vandaag blijft het droog met af en toe zon. Het wordt ongeveer vijftien graden. Maar let op: vanavond gaat het hard waaien, vooral aan de kust. Er komt een storm aan uit het westen. Zet uw fiets binnen en maak losse spullen in de tuin goed vast. Morgenochtend regent het flink, dus neem uw regenjas mee naar het werk. In de middag wordt het langzaam weer rustig en droog. Tot morgen.`,
    qs: [
      { q: 'Hoe is het weer vandaag overdag?', o: ['Droog met af en toe zon', 'De hele dag regen', 'Erg koud met sneeuw'], a: 0 },
      { q: 'Wat gebeurt er vanavond?', o: ['Het gaat sneeuwen', 'Het gaat hard waaien', 'Het wordt warmer'], a: 1 },
      { q: 'Waar wordt de wind het sterkst?', o: ['In het oosten', 'In de stad', 'Aan de kust'], a: 2 },
      { q: 'Wat is het advies voor morgenochtend?', o: ['Een regenjas meenemen', 'Binnen blijven', 'Een zonnebril meenemen'], a: 0 },
    ],
  },
  {
    id: 'a2l36',
    type: 'bericht',
    script: `Dit is de verkeersinformatie van tien uur. Op de A12 richting Den Haag staat een file van acht kilometer door een ongeluk met een vrachtwagen. De weg is daar gedeeltelijk dicht en u verliest ongeveer een half uur. Rijd liever via de A4, daar is het rustig. In het centrum van Utrecht is de Stationsweg vandaag afgesloten vanwege werkzaamheden. Fietsers en voetgangers kunnen er wel langs. Het openbaar vervoer rijdt overal gewoon op tijd. Over een uur volgt er nieuwe informatie.`,
    qs: [
      { q: 'Waardoor staat er een file op de A12?', o: ['Door een ongeluk met een vrachtwagen', 'Door werkzaamheden', 'Door slecht weer'], a: 0 },
      { q: 'Hoeveel tijd verliezen automobilisten daar?', o: ['Een kwartier', 'Ongeveer een half uur', 'Een uur'], a: 1 },
      { q: 'Welke weg is een goed alternatief?', o: ['De A2', 'De A12', 'De A4'], a: 2 },
      { q: 'Wie kan er wel door de Stationsweg?', o: ['Fietsers en voetgangers', 'Alleen bussen', 'Niemand'], a: 0 },
      { q: 'Wanneer komt er nieuwe verkeersinformatie?', o: ['Over een half uur', 'Over een uur', 'Morgenochtend'], a: 1 },
    ],
  },
  {
    id: 'a2l37',
    type: 'bericht',
    script: `En dan nog een bericht uit de regio. Komend weekend is het zomerfeest in het centrum van Meerdijk. Op zaterdag en zondag staan er kraampjes met eten uit de hele wereld, en op het plein staat een groot podium met muziek. Het feest begint zaterdag om twaalf uur. De binnenstad is beide dagen autovrij. Bezoekers kunnen gratis parkeren bij het station en reizen dan met een gratis bus naar het centrum. De organisatie verwacht ongeveer tienduizend bezoekers.`,
    qs: [
      { q: 'Waar is het zomerfeest?', o: ['In het centrum van Meerdijk', 'Bij het station', 'In een park'], a: 0 },
      { q: 'Hoe laat begint het feest op zaterdag?', o: ['Om tien uur', 'Om twaalf uur', 'Om twee uur'], a: 1 },
      { q: 'Wat kunnen bezoekers op het plein doen?', o: ['Naar muziek luisteren', 'Sporten', 'Een film kijken'], a: 0 },
      { q: 'Hoe komen bezoekers van het station naar het centrum?', o: ['Met de tram', 'Lopend', 'Met een gratis bus'], a: 2 },
      { q: 'Hoeveel bezoekers verwacht de organisatie?', o: ['Duizend', 'Vijfduizend', 'Tienduizend'], a: 2 },
    ],
  },
  {
    id: 'a2l38',
    type: 'bericht',
    script: `Goed nieuws voor kinderen in de wijk Oosterpark. Vanmiddag opent wethouder Berends de nieuwe speeltuin aan de Lindelaan. De oude speeltuin was kapot en is helemaal vernieuwd. Er zijn nu klimtoestellen, twee glijbanen en een grote zandbak. Bewoners uit de wijk mochten zelf meedenken over de plannen. De opening begint om vier uur, na schooltijd. Alle kinderen krijgen een gratis ijsje en er is een springkussen. De speeltuin is elke dag open van negen uur ’s ochtends tot acht uur ’s avonds.`,
    qs: [
      { q: 'Wat wordt er vanmiddag geopend?', o: ['Een nieuwe speeltuin', 'Een nieuwe school', 'Een nieuw park'], a: 0 },
      { q: 'Wie opent de speeltuin?', o: ['De burgemeester', 'De wethouder', 'Een juf van school'], a: 1 },
      { q: 'Wie mochten meedenken over de plannen?', o: ['De kinderen van school', 'De gemeenteraad', 'De bewoners van de wijk'], a: 2 },
      { q: 'Wat krijgen de kinderen bij de opening?', o: ['Een gratis ijsje', 'Een ballon', 'Een cadeautje'], a: 0 },
      { q: 'Hoe laat begint de opening?', o: ['Om drie uur', 'Om vier uur', 'Om vijf uur'], a: 1 },
    ],
  },
  {
    id: 'a2l39',
    type: 'bericht',
    script: `Een bericht van de gemeente Veldhoven. Zaterdag is het weer de jaarlijkse compostdag. Inwoners kunnen dan gratis compost ophalen voor de tuin. Dit is een bedankje, omdat inwoners hun groente- en fruitafval zo goed scheiden. U kunt terecht op de gemeentewerf aan de Industrieweg, tussen negen en vier uur. Neem zelf een schep en zakken mee, of kom met een aanhanger. Er geldt een maximum van drie zakken per adres. Vergeet uw legitimatie niet, want de actie is alleen voor inwoners van Veldhoven.`,
    qs: [
      { q: 'Wat kunnen inwoners zaterdag gratis ophalen?', o: ['Compost', 'Planten', 'Zand'], a: 0 },
      { q: 'Waarom krijgen de inwoners dit cadeau?', o: ['Omdat de gemeente jarig is', 'Omdat zij hun afval goed scheiden', 'Omdat de lente begint'], a: 1 },
      { q: 'Wat moeten inwoners zelf meenemen?', o: ['Een schep en zakken', 'Geld', 'Een volle afvalbak'], a: 0 },
      { q: 'Hoeveel zakken mag je per adres meenemen?', o: ['Twee', 'Vier', 'Drie'], a: 2 },
      { q: 'Waarom moet je je legitimatie meenemen?', o: ['De actie is alleen voor inwoners van Veldhoven', 'De compost is anders niet gratis', 'Het is druk op de gemeentewerf'], a: 0 },
    ],
  },
  {
    id: 'a2l40',
    type: 'bericht',
    script: `Tot slot een waarschuwing van het weerbureau. Het wordt de komende dagen erg warm: morgen dertig graden en overmorgen zelfs drieëndertig graden. Het advies is: drink veel water, ook als u geen dorst heeft. Blijf tussen twaalf en vier uur zoveel mogelijk uit de zon. Denk ook aan ouderen in uw buurt en vraag of zij hulp nodig hebben. Voor kinderen geldt: smeer ze goed in en laat ze niet te lang buiten spelen. Woensdag komt er onweer en wordt het gelukkig weer koeler.`,
    qs: [
      { q: 'Waarvoor waarschuwt het weerbureau?', o: ['Voor erg warm weer', 'Voor gladde wegen', 'Voor zware storm'], a: 0 },
      { q: 'Hoe warm wordt het overmorgen?', o: ['Dertig graden', 'Drieëndertig graden', 'Vijfentwintig graden'], a: 1 },
      { q: 'Wanneer kun je beter uit de zon blijven?', o: ['Tussen twaalf en vier uur', 'In de vroege ochtend', 'Na zes uur ’s avonds'], a: 0 },
      { q: 'Wat is het advies over ouderen in de buurt?', o: ['Ze elke dag water brengen', 'Vragen of zij hulp nodig hebben', 'Ze naar binnen brengen'], a: 1 },
      { q: 'Wanneer wordt het weer koeler?', o: ['Morgen', 'Vrijdag', 'Woensdag'], a: 2 },
    ],
  },
];
