// B1 (Staatsexamen NT2 Programma I) source bank: writing and speaking tasks.
// t: 'zin' = finish the sentence, 'msg' = short e-mail/letter with 3 content points,
// 'open' = longer free text. Spreken: t: 'sp', sec 20 (short) or 30 (medium).
// kw = array of GROUPS; a group matches when ALL its words occur, a point scores when ANY group matches.

export const SCHRIJVEN = [
  // ---------- zinstaken (26) ----------
  { t: 'zin', q: 'Maak de zin af: Ik heb gesolliciteerd op deze functie, omdat …', min: 5, model: 'Ik heb gesolliciteerd op deze functie, omdat ik al vijf jaar ervaring heb in de logistiek.' },
  { t: 'zin', q: 'Maak de zin af: Als ik meer werkervaring had, dan …', min: 5, model: 'Als ik meer werkervaring had, dan zou ik sneller een vast contract krijgen.' },
  { t: 'zin', q: 'Maak de zin af: Ik wil graag een cursus Nederlands volgen, zodat …', min: 5, model: 'Ik wil graag een cursus Nederlands volgen, zodat ik makkelijker met klanten kan praten.' },
  { t: 'zin', q: 'Maak de zin af: Mijn vorige werkgever was tevreden over mij, want …', min: 5, model: 'Mijn vorige werkgever was tevreden over mij, want ik kwam altijd op tijd en werkte netjes.' },
  { t: 'zin', q: 'Maak de zin af: Hoewel het salaris wat lager is, …', min: 5, model: 'Hoewel het salaris wat lager is, neem ik de baan toch, omdat ik veel kan leren.' },
  { t: 'zin', q: 'Maak de zin af: Ik kan pas na vijf uur bij de gemeente langskomen, omdat …', min: 5, model: 'Ik kan pas na vijf uur bij de gemeente langskomen, omdat ik tot half vijf werk.' },
  { t: 'zin', q: 'Maak de zin af: Voordat ik naar Nederland kwam, …', min: 4, model: 'Voordat ik naar Nederland kwam, werkte ik als verpleegkundige in een groot ziekenhuis.' },
  { t: 'zin', q: 'Maak de zin af: Sinds ik in deze wijk woon, …', min: 4, model: 'Sinds ik in deze wijk woon, heb ik veel nieuwe mensen leren kennen.' },
  { t: 'zin', q: 'Maak de zin af: Ik heb de brief van de Belastingdienst niet goed begrepen, daarom …', min: 5, model: 'Ik heb de brief van de Belastingdienst niet goed begrepen, daarom heb ik om hulp gevraagd bij het buurthuis.' },
  { t: 'zin', q: 'Maak de zin af: Als u het niet eens bent met de beslissing, …', min: 5, model: 'Als u het niet eens bent met de beslissing, kunt u binnen zes weken bezwaar maken.' },
  { t: 'zin', q: 'Maak de zin af: Ik zou graag meer uren willen werken, maar …', min: 5, model: 'Ik zou graag meer uren willen werken, maar ik moet mijn kinderen om vier uur ophalen.' },
  { t: 'zin', q: 'Maak de zin af: Het grootste voordeel van het openbaar vervoer is dat …', min: 5, model: 'Het grootste voordeel van het openbaar vervoer is dat je geen parkeerplaats hoeft te zoeken.' },
  { t: 'zin', q: 'Maak de zin af: Toen ik voor het eerst met mijn nieuwe collega\'s sprak, …', min: 5, model: 'Toen ik voor het eerst met mijn nieuwe collega\'s sprak, was ik erg zenuwachtig.' },
  { t: 'zin', q: 'Maak de zin af: Ik heb mijn afspraak bij de huisarts verzet, omdat …', min: 5, model: 'Ik heb mijn afspraak bij de huisarts verzet, omdat ik die ochtend moest werken.' },
  { t: 'zin', q: 'Maak de zin af: Volgens mij is het belangrijk dat kinderen …', min: 5, model: 'Volgens mij is het belangrijk dat kinderen elke dag buiten spelen.' },
  { t: 'zin', q: 'Maak de zin af: Nadat ik mijn diploma had gehaald, …', min: 4, model: 'Nadat ik mijn diploma had gehaald, ben ik meteen gaan solliciteren.' },
  { t: 'zin', q: 'Maak de zin af: Ik zou deze opleiding aan anderen aanraden, omdat …', min: 5, model: 'Ik zou deze opleiding aan anderen aanraden, omdat je veel praktijkervaring opdoet.' },
  { t: 'zin', q: 'Maak de zin af: Als de huur volgend jaar weer omhooggaat, …', min: 5, model: 'Als de huur volgend jaar weer omhooggaat, moet ik op zoek naar een goedkopere woning.' },
  { t: 'zin', q: 'Maak de zin af: Ik ben het niet eens met dit voorstel, want …', min: 5, model: 'Ik ben het niet eens met dit voorstel, want er is te weinig overleg geweest met het personeel.' },
  { t: 'zin', q: 'Maak de zin af: Wat mij op mijn werk het meest is opgevallen, is dat …', min: 5, model: 'Wat mij op mijn werk het meest is opgevallen, is dat iedereen elkaar bij de voornaam noemt.' },
  { t: 'zin', q: 'Maak de zin af: Ik heb mijn verzekering opgezegd, omdat …', min: 5, model: 'Ik heb mijn verzekering opgezegd, omdat ik elders een veel goedkoper pakket kon krijgen.' },
  { t: 'zin', q: 'Maak de zin af: Zodra ik mijn diploma inburgering heb, …', min: 4, model: 'Zodra ik mijn diploma inburgering heb, wil ik een mbo-opleiding gaan doen.' },
  { t: 'zin', q: 'Maak de zin af: Ik vind het lastig om instanties te bellen, omdat …', min: 5, model: 'Ik vind het lastig om instanties te bellen, omdat ik de moeilijke woorden vaak niet begrijp.' },
  { t: 'zin', q: 'Maak de zin af: Als mijn buren opnieuw geluidsoverlast veroorzaken, …', min: 5, model: 'Als mijn buren opnieuw geluidsoverlast veroorzaken, meld ik het bij de woningcorporatie.' },
  { t: 'zin', q: 'Maak de zin af: Een groot verschil tussen mijn geboorteland en Nederland is dat …', min: 6, model: 'Een groot verschil tussen mijn geboorteland en Nederland is dat hier bijna iedereen met de fiets naar het werk gaat.' },
  { t: 'zin', q: 'Maak de zin af: Ik heb bezwaar gemaakt tegen de boete, omdat …', min: 5, model: 'Ik heb bezwaar gemaakt tegen de boete, omdat ik wel degelijk een geldig parkeerkaartje had gekocht.' },

  // ---------- deelschrijftaken / korte e-mails en brieven (24) ----------
  {
    t: 'msg',
    q: 'Schrijf een e-mail aan uw leidinggevende. Schrijf: (1) dat u een cursus wilt volgen, (2) waarom de cursus nuttig is voor uw werk, (3) vraag of het bedrijf de kosten betaalt.',
    pts: [
      { d: 'U schrijft dat u een cursus wilt volgen', kw: [['cursus'], ['opleiding'], ['training']] },
      { d: 'U legt uit waarom de cursus nuttig is', kw: [['omdat'], ['want'], ['nuttig'], ['beter']] },
      { d: 'U vraagt naar de kosten', kw: [['kosten'], ['betaal'], ['vergoed']] },
    ],
    min: 40,
    model: 'Geachte mevrouw De Vries,\n\nGraag zou ik in het najaar de cursus klantcommunicatie volgen. De cursus is nuttig voor mijn werk, omdat ik klanten aan de telefoon dan beter kan helpen. Kunt u mij laten weten of het bedrijf de kosten vergoedt?\n\nMet vriendelijke groet,\nSamir Yildiz',
  },
  {
    t: 'msg',
    q: 'Schrijf een e-mail aan uw verhuurder. Schrijf: (1) dat er een lekkage in de badkamer is, (2) sinds wanneer het probleem er is, (3) vraag of er snel een monteur kan komen.',
    pts: [
      { d: 'U meldt de lekkage', kw: [['lekkage'], ['lekt'], ['water'], ['nat']] },
      { d: 'U schrijft sinds wanneer', kw: [['sinds'], ['week'], ['gisteren'], ['dagen']] },
      { d: 'U vraagt om een monteur', kw: [['monteur'], ['loodgieter'], ['reparatie'], ['repareren']] },
    ],
    min: 40,
    model: 'Geachte heer Bakker,\n\nIn mijn badkamer is een lekkage onder de wastafel. Het probleem is er sinds vorige week donderdag en de vloer wordt steeds natter. Kunt u zo snel mogelijk een loodgieter langs sturen?\n\nMet vriendelijke groet,\nNadia Haddad',
  },
  {
    t: 'msg',
    q: 'Schrijf een e-mail aan de gemeente. Schrijf: (1) dat u gaat verhuizen en per welke datum, (2) wat uw nieuwe adres wordt, (3) vraag welke documenten u moet meenemen.',
    pts: [
      { d: 'U geeft de verhuizing door', kw: [['verhuis'], ['verhuizen'], ['verhuizing']] },
      { d: 'U noemt uw nieuwe adres', kw: [['nieuwe', 'adres'], ['straat'], ['postcode']] },
      { d: 'U vraagt welke documenten nodig zijn', kw: [['documenten'], ['papieren'], ['meenemen'], ['nodig']] },
    ],
    min: 40,
    model: 'Geachte heer/mevrouw,\n\nPer 1 mei verhuis ik binnen de gemeente. Mijn nieuwe adres wordt Kerkstraat 18, 3512 AB Utrecht. Kunt u mij laten weten welke documenten ik mee moet nemen als ik de verhuizing aan de balie doorgeef?\n\nMet vriendelijke groet,\nOmar Kaya',
  },
  {
    t: 'msg',
    q: 'Schrijf een korte brief aan uw buren. Schrijf: (1) dat u last hebt van geluid, (2) wanneer dat vooral is, (3) stel voor om er samen over te praten.',
    pts: [
      { d: 'U schrijft dat u last hebt van geluid', kw: [['geluid'], ['lawaai'], ['overlast'], ['muziek']] },
      { d: 'U schrijft wanneer de overlast is', kw: [['avond'], ['nacht'], ['weekend'], ['uur']] },
      { d: 'U stelt een gesprek voor', kw: [['praten'], ['gesprek'], ['langskomen'], ['oplossing']] },
    ],
    min: 40,
    model: 'Beste buren,\n\nIk woon onder u en heb de laatste tijd behoorlijk last van geluid. Vooral in het weekend staat de muziek na elf uur \'s avonds erg hard. Zullen we er een keer rustig over praten? Ik ben doordeweeks na zes uur thuis.\n\nMet vriendelijke groet,\nEva Simons',
  },
  {
    t: 'msg',
    q: 'Schrijf een e-mail aan de school van uw kind. Schrijf: (1) dat uw kind ziek is, (2) hoelang hij of zij waarschijnlijk afwezig is, (3) vraag om het huiswerk.',
    pts: [
      { d: 'U meldt uw kind ziek', kw: [['ziek'], ['griep'], ['koorts']] },
      { d: 'U schrijft hoelang', kw: [['dagen'], ['week'], ['morgen'], ['maandag']] },
      { d: 'U vraagt om het huiswerk', kw: [['huiswerk'], ['opdrachten'], ['lesstof']] },
    ],
    min: 38,
    model: 'Geachte mevrouw Jansen,\n\nMijn dochter Amira is ziek en heeft koorts. Waarschijnlijk blijft zij deze week thuis; maandag verwacht ik haar weer op school. Kunt u het huiswerk van deze week naar mij mailen, zodat zij niets mist?\n\nMet vriendelijke groet,\nLeyla Demir',
  },
  {
    t: 'msg',
    q: 'Schrijf een e-mail aan uw werkgever. Schrijf: (1) dat u verlof wilt opnemen, (2) om welke dagen het gaat, (3) waarom u die dagen vrij wilt.',
    pts: [
      { d: 'U vraagt verlof aan', kw: [['verlof'], ['vrij'], ['vakantie']] },
      { d: 'U noemt de dagen', kw: [['dagen'], ['week'], ['juli'], ['van', 'tot']] },
      { d: 'U geeft de reden', kw: [['omdat'], ['want'], ['bruiloft'], ['familie'], ['reden']] },
    ],
    min: 38,
    model: 'Beste Karin,\n\nGraag zou ik verlof opnemen van maandag 14 juli tot en met vrijdag 18 juli. Ik vraag deze week vrij, omdat mijn broer in het buitenland gaat trouwen. Kun je mij laten weten of dit past in de planning?\n\nMet vriendelijke groet,\nPiotr Nowak',
  },
  {
    t: 'msg',
    q: 'Schrijf een e-mail aan uw zorgverzekeraar. Schrijf: (1) dat u een rekening hebt gekregen die niet klopt, (2) om welk bedrag het gaat, (3) vraag om uitleg.',
    pts: [
      { d: 'U meldt dat de rekening niet klopt', kw: [['rekening'], ['nota'], ['factuur']] },
      { d: 'U noemt het bedrag', kw: [['euro'], ['bedrag']] },
      { d: 'U vraagt om uitleg', kw: [['uitleg'], ['uitleggen'], ['controleren'], ['klopt']] },
    ],
    min: 40,
    model: 'Geachte heer/mevrouw,\n\nVorige week ontving ik een rekening die volgens mij niet klopt. Het gaat om een bedrag van 235 euro voor fysiotherapie die ik niet heb gehad. Kunt u dit controleren en mij uitleggen waar deze kosten vandaan komen?\n\nMet vriendelijke groet,\nHenk Vermeulen',
  },
  {
    t: 'msg',
    q: 'Schrijf een e-mail aan uw sportclub. Schrijf: (1) dat u uw lidmaatschap wilt opzeggen, (2) per wanneer, (3) waarom u stopt.',
    pts: [
      { d: 'U zegt het lidmaatschap op', kw: [['opzeggen'], ['stoppen'], ['lidmaatschap'], ['beëindigen']] },
      { d: 'U schrijft per wanneer', kw: [['per'], ['januari'], ['maand'], ['datum']] },
      { d: 'U geeft de reden', kw: [['omdat'], ['want'], ['tijd'], ['verhuis'], ['blessure']] },
    ],
    min: 35,
    model: 'Geachte heer/mevrouw,\n\nHierbij zeg ik mijn lidmaatschap op, per 1 januari. Ik stop, omdat ik door mijn nieuwe werktijden bijna nooit meer kan trainen. Wilt u mij een bevestiging sturen?\n\nMet vriendelijke groet,\nJoost Peters',
  },
  {
    t: 'msg',
    q: 'Schrijf een e-mail aan een collega. Schrijf: (1) dat u een dienst wilt ruilen, (2) om welke dag het gaat, (3) bedank uw collega alvast.',
    pts: [
      { d: 'U vraagt om te ruilen', kw: [['ruilen'], ['ruil'], ['overnemen'], ['dienst']] },
      { d: 'U noemt de dag', kw: [['zaterdag'], ['dinsdag'], ['dag'], ['datum']] },
      { d: 'U bedankt uw collega', kw: [['bedankt'], ['dank'], ['alvast']] },
    ],
    min: 35,
    model: 'Hoi Marleen,\n\nZou jij zaterdag mijn dienst willen overnemen? Ik werk dan van 8.00 tot 16.00 uur, maar ik moet die dag met mijn moeder naar het ziekenhuis. Ik neem graag een dienst van jou terug. Alvast bedankt!\n\nGroeten,\nAli',
  },
  {
    t: 'msg',
    q: 'Schrijf een e-mail aan een opleidingsinstituut. Schrijf: (1) dat u informatie wilt over de avondcursus, (2) welk niveau u zoekt, (3) vraag naar de kosten en de lestijden.',
    pts: [
      { d: 'U vraagt om informatie over de cursus', kw: [['informatie'], ['inlichtingen'], ['cursus']] },
      { d: 'U noemt het niveau', kw: [['niveau'], ['b1'], ['beginner'], ['gevorderd']] },
      { d: 'U vraagt naar kosten en lestijden', kw: [['kosten'], ['prijs'], ['lestijden'], ['tijden']] },
    ],
    min: 38,
    model: 'Geachte heer/mevrouw,\n\nGraag ontvang ik informatie over uw avondcursus Nederlands. Ik zoek een cursus op niveau B1, want ik heb A2 vorig jaar afgerond. Kunt u mij laten weten wat de kosten zijn en op welke avonden de lessen zijn?\n\nMet vriendelijke groet,\nMaria Costa',
  },
  {
    t: 'msg',
    q: 'Schrijf een e-mail aan de huisartsenpraktijk. Schrijf: (1) dat u uw afspraak wilt verzetten, (2) waarom dat nodig is, (3) noem een dag die u wel schikt.',
    pts: [
      { d: 'U wilt de afspraak verzetten', kw: [['verzetten'], ['verplaatsen'], ['afspraak'], ['annuleren']] },
      { d: 'U geeft de reden', kw: [['omdat'], ['want'], ['werk'], ['ziek']] },
      { d: 'U noemt een nieuwe dag', kw: [['dinsdag'], ['woensdag'], ['volgende', 'week'], ['nieuwe', 'afspraak']] },
    ],
    min: 35,
    model: 'Geachte heer/mevrouw,\n\nIk heb woensdag om 9.15 uur een afspraak bij dokter Willems, maar die kan ik helaas niet nakomen. Ik moet die ochtend onverwacht werken. Zou de afspraak verzet kunnen worden naar dinsdagmiddag volgende week?\n\nMet vriendelijke groet,\nRosa Martins',
  },
  {
    t: 'msg',
    q: 'Schrijf een e-mail aan een webwinkel. Schrijf: (1) dat het product beschadigd is aangekomen, (2) wat uw bestelnummer is, (3) vraag om een nieuw product of om uw geld terug.',
    pts: [
      { d: 'U meldt dat het product beschadigd is', kw: [['beschadigd'], ['kapot'], ['stuk'], ['schade']] },
      { d: 'U noemt het bestelnummer', kw: [['bestelnummer'], ['bestelling'], ['nummer'], ['order']] },
      { d: 'U vraagt om vervanging of geld terug', kw: [['vervangen'], ['nieuw'], ['geld', 'terug'], ['terugbetalen']] },
    ],
    min: 40,
    model: 'Geachte heer/mevrouw,\n\nGisteren ontving ik de bureaustoel die ik bij u besteld heb, maar de rugleuning is beschadigd. Mijn bestelnummer is 8842019. Ik ontvang graag een nieuwe stoel; is dat niet mogelijk, dan krijg ik liever mijn geld terug.\n\nMet vriendelijke groet,\nDavid Okoye',
  },
  {
    t: 'msg',
    q: 'Schrijf een e-mail aan de gemeente over een parkeerboete. Schrijf: (1) dat u bezwaar maakt, (2) wat er precies gebeurd is, (3) vraag of de boete ingetrokken kan worden.',
    pts: [
      { d: 'U maakt bezwaar', kw: [['bezwaar'], ['niet', 'eens'], ['boete']] },
      { d: 'U legt uit wat er gebeurd is', kw: [['omdat'], ['want'], ['kaartje'], ['automaat'], ['gebeurd']] },
      { d: 'U vraagt de boete in te trekken', kw: [['intrekken'], ['annuleren'], ['kwijtschelden'], ['terugbetalen']] },
    ],
    min: 45,
    model: 'Geachte heer/mevrouw,\n\nHierbij maak ik bezwaar tegen parkeerboete nummer 55231. Ik had wel degelijk betaald, maar de automaat gaf geen kaartje; van die storing heb ik een foto gemaakt. Ik verzoek u daarom de boete in te trekken.\n\nMet vriendelijke groet,\nSonia Petrova',
  },
  {
    t: 'msg',
    q: 'Schrijf een e-mail aan een uitzendbureau. Schrijf: (1) dat u werk zoekt, (2) welke ervaring u hebt, (3) wanneer u kunt beginnen.',
    pts: [
      { d: 'U schrijft dat u werk zoekt', kw: [['werk'], ['baan'], ['functie'], ['vacature']] },
      { d: 'U noemt uw ervaring', kw: [['ervaring'], ['gewerkt'], ['jaar'], ['diploma']] },
      { d: 'U schrijft wanneer u kunt beginnen', kw: [['beschikbaar'], ['beginnen'], ['direct'], ['vanaf']] },
    ],
    min: 40,
    model: 'Geachte heer/mevrouw,\n\nVia uw website zag ik dat u regelmatig magazijnmedewerkers zoekt. Ik heb drie jaar in een distributiecentrum gewerkt en beschik over een heftruckcertificaat. Ik ben per direct beschikbaar voor 32 uur per week.\n\nMet vriendelijke groet,\nIbrahim Diallo',
  },
  {
    t: 'msg',
    q: 'Schrijf een e-mail aan uw bank. Schrijf: (1) dat u uw bankpas kwijt bent, (2) wanneer u dat gemerkt hebt, (3) vraag om een nieuwe pas.',
    pts: [
      { d: 'U meldt dat de pas kwijt is', kw: [['bankpas'], ['pinpas'], ['pas'], ['kwijt']] },
      { d: 'U schrijft wanneer u het merkte', kw: [['gisteren'], ['vanmorgen'], ['weekend'], ['gemerkt'], ['ontdekt']] },
      { d: 'U vraagt om een nieuwe pas', kw: [['nieuwe'], ['aanvragen'], ['sturen'], ['blokkeren']] },
    ],
    min: 35,
    model: 'Geachte heer/mevrouw,\n\nIk ben mijn bankpas kwijt. Gisteravond merkte ik in de supermarkt dat de pas niet meer in mijn portemonnee zat. Ik heb hem via de app geblokkeerd en wil graag een nieuwe pas aanvragen.\n\nMet vriendelijke groet,\nAnita Rusu',
  },
  {
    t: 'msg',
    q: 'Schrijf een e-mail aan de woningcorporatie. Schrijf: (1) dat u een beugel in de douche nodig hebt, (2) waarom u die nodig hebt, (3) vraag wanneer iemand kan langskomen.',
    pts: [
      { d: 'U vraagt om een aanpassing in de badkamer', kw: [['beugel'], ['aanpassing'], ['badkamer'], ['douche']] },
      { d: 'U legt uit waarom', kw: [['omdat'], ['want'], ['gezondheid'], ['vallen'], ['moeilijk']] },
      { d: 'U vraagt wanneer iemand langskomt', kw: [['langskomen'], ['afspraak'], ['wanneer'], ['monteur']] },
    ],
    min: 40,
    model: 'Geachte heer/mevrouw,\n\nGraag zou ik een beugel in de douche laten plaatsen. Sinds mijn heupoperatie sta ik onvast en ben ik al twee keer bijna gevallen. Kunt u mij laten weten wanneer een monteur kan langskomen?\n\nMet vriendelijke groet,\nGerda Brouwer',
  },
  {
    t: 'msg',
    q: 'Schrijf een e-mail aan uw leidinggevende. Schrijf: (1) dat u zich ziek meldt, (2) wat er aan de hand is, (3) wanneer u denkt weer te kunnen werken.',
    pts: [
      { d: 'U meldt zich ziek', kw: [['ziek'], ['ziekmelden'], ['niet', 'werken']] },
      { d: 'U vertelt wat er is', kw: [['koorts'], ['griep'], ['rug'], ['klachten'], ['buikpijn']] },
      { d: 'U schrijft wanneer u terug denkt te zijn', kw: [['morgen'], ['maandag'], ['dagen'], ['terug'], ['weer', 'werken']] },
    ],
    min: 35,
    model: 'Beste Rick,\n\nIk moet mij vandaag ziek melden. Ik heb sinds gisteravond koorts en veel hoofdpijn, dus werken lukt echt niet. Ik verwacht overmorgen weer te kunnen beginnen en hou je op de hoogte.\n\nMet vriendelijke groet,\nFatima Ouali',
  },
  {
    t: 'msg',
    q: 'Schrijf een e-mail aan de docent van uw kind. Schrijf: (1) dat u een gesprek wilt over de resultaten, (2) waarom u zich zorgen maakt, (3) stel een dag en tijd voor.',
    pts: [
      { d: 'U vraagt om een gesprek', kw: [['gesprek'], ['afspraak'], ['spreken']] },
      { d: 'U legt uit waarom u zich zorgen maakt', kw: [['zorgen'], ['cijfers'], ['resultaten'], ['moeite']] },
      { d: 'U stelt een moment voor', kw: [['donderdag'], ['uur'], ['middag'], ['schikt']] },
    ],
    min: 40,
    model: 'Geachte heer Smit,\n\nGraag zou ik met u spreken over de resultaten van mijn zoon Yusuf. Ik maak mij zorgen, omdat zijn cijfers voor rekenen sinds de kerstvakantie flink zijn gedaald. Zou donderdag om 15.30 uur u schikken?\n\nMet vriendelijke groet,\nHalima Aziz',
  },
  {
    t: 'msg',
    q: 'Schrijf een e-mail aan de bibliotheek. Schrijf: (1) dat u een zaal wilt reserveren voor een buurtbijeenkomst, (2) op welke datum en hoe laat, (3) hoeveel mensen er komen.',
    pts: [
      { d: 'U wilt een zaal reserveren', kw: [['zaal'], ['ruimte'], ['reserveren']] },
      { d: 'U noemt datum en tijd', kw: [['maart'], ['datum'], ['uur'], ['avond']] },
      { d: 'U noemt het aantal mensen', kw: [['mensen'], ['personen'], ['deelnemers'], ['bezoekers']] },
    ],
    min: 38,
    model: 'Geachte heer/mevrouw,\n\nNamens onze buurtvereniging wil ik graag een zaal reserveren voor een bijeenkomst over veiligheid in de wijk. Het gaat om woensdag 12 maart van 19.30 tot 21.30 uur. Wij verwachten ongeveer 25 personen.\n\nMet vriendelijke groet,\nTom de Wit',
  },
  {
    t: 'msg',
    q: 'Schrijf een e-mail aan een goede kennis. Schrijf: (1) dat u gaat verhuizen, (2) wanneer dat is, (3) vraag of hij of zij kan helpen met tillen.',
    pts: [
      { d: 'U schrijft dat u gaat verhuizen', kw: [['verhuis'], ['verhuizen'], ['nieuwe', 'woning']] },
      { d: 'U noemt de datum', kw: [['zaterdag'], ['datum'], ['april'], ['volgende', 'maand']] },
      { d: 'U vraagt om hulp', kw: [['helpen'], ['hulp'], ['tillen'], ['meehelpen']] },
    ],
    min: 35,
    model: 'Hoi Bram,\n\nEindelijk is het zover: ik verhuis naar een appartement in Zuid. De verhuizing is zaterdag 5 april, vanaf negen uur \'s ochtends. Zou jij die dag kunnen helpen met tillen? Voor koffie en pizza wordt gezorgd.\n\nGroeten,\nSelin',
  },
  {
    t: 'msg',
    q: 'Schrijf een e-mail aan een vervoersbedrijf. Schrijf: (1) dat uw trein veel vertraging had, (2) om welke reis het ging, (3) vraag om een vergoeding.',
    pts: [
      { d: 'U meldt de vertraging', kw: [['vertraging'], ['te', 'laat'], ['uitgevallen']] },
      { d: 'U noemt de reis', kw: [['trein'], ['reis'], ['traject'], ['station']] },
      { d: 'U vraagt om een vergoeding', kw: [['vergoeding'], ['geld', 'terug'], ['compensatie'], ['vergoeden']] },
    ],
    min: 40,
    model: 'Geachte heer/mevrouw,\n\nOp dinsdag 3 juni had mijn trein ruim een uur vertraging. Het ging om de reis van Eindhoven naar Amsterdam Centraal van 7.12 uur, waardoor ik een belangrijke afspraak heb gemist. Ik verzoek u het ticketbedrag te vergoeden.\n\nMet vriendelijke groet,\nJan Klaassen',
  },
  {
    t: 'msg',
    q: 'Schrijf een e-mail aan de afdeling personeelszaken. Schrijf: (1) dat uw contract binnenkort afloopt, (2) wanneer dat is, (3) vraag of het contract verlengd wordt.',
    pts: [
      { d: 'U noemt uw contract', kw: [['contract'], ['aanstelling']] },
      { d: 'U schrijft wanneer het afloopt', kw: [['afloopt'], ['eindigt'], ['juni'], ['maand'], ['datum']] },
      { d: 'U vraagt naar verlenging', kw: [['verlengd'], ['verlengen'], ['vast'], ['nieuw', 'contract']] },
    ],
    min: 35,
    model: 'Geachte mevrouw Bos,\n\nMijn tijdelijke contract als medewerker planning loopt af op 30 juni. Omdat ik het werk met veel plezier doe, hoor ik graag of verlenging mogelijk is. Kunt u mij hierover binnenkort informeren?\n\nMet vriendelijke groet,\nEmine Aksoy',
  },
  {
    t: 'msg',
    q: 'Schrijf een e-mail aan uw energieleverancier. Schrijf: (1) dat uw maandbedrag te hoog is, (2) wat uw meterstand is, (3) vraag of het bedrag verlaagd kan worden.',
    pts: [
      { d: 'U schrijft dat het maandbedrag te hoog is', kw: [['maandbedrag'], ['termijnbedrag'], ['te', 'hoog']] },
      { d: 'U geeft de meterstand door', kw: [['meterstand'], ['meter'], ['stand'], ['kwh']] },
      { d: 'U vraagt om verlaging', kw: [['verlagen'], ['aanpassen'], ['lager'], ['wijzigen']] },
    ],
    min: 40,
    model: 'Geachte heer/mevrouw,\n\nMijn maandbedrag van 210 euro is naar mijn idee veel te hoog voor onze kleine woning. De meterstand is vandaag 41.230 kWh voor elektriciteit en 4.180 m3 voor gas. Kunt u het maandbedrag op basis daarvan verlagen?\n\nMet vriendelijke groet,\nMarcin Wozniak',
  },
  {
    t: 'msg',
    q: 'Schrijf een e-mail aan de gemeente over uw inburgering. Schrijf: (1) dat u uitstel wilt voor uw examen, (2) waarom u meer tijd nodig hebt, (3) vraag wat u daarvoor moet doen.',
    pts: [
      { d: 'U vraagt om uitstel', kw: [['uitstel'], ['verlenging'], ['meer', 'tijd']] },
      { d: 'U legt uit waarom', kw: [['omdat'], ['want'], ['ziek'], ['werk'], ['zorg']] },
      { d: 'U vraagt wat u moet doen', kw: [['formulier'], ['aanvragen'], ['moet', 'doen'], ['stappen'], ['nodig']] },
    ],
    min: 45,
    model: 'Geachte heer/mevrouw,\n\nGraag vraag ik uitstel aan voor mijn inburgeringsexamen. Ik heb meer tijd nodig, omdat ik een half jaar ziek ben geweest en daardoor veel lessen heb gemist. Kunt u mij uitleggen welk formulier ik moet invullen en welke bewijsstukken ik moet meesturen?\n\nMet vriendelijke groet,\nRachid El Amrani',
  },

  // ---------- open schrijfopdrachten (10) ----------
  { t: 'open', q: 'Schrijf ongeveer zes zinnen over de voordelen en de nadelen van thuiswerken.', min: 55, model: 'Thuiswerken heeft duidelijke voordelen. Je verliest geen tijd in de file en je kunt rustiger werken. Ook is het makkelijker om werk en gezin te combineren. Toch zijn er nadelen. Je ziet je collega\'s minder, waardoor overleg lastiger wordt. Zelf werk ik het liefst twee dagen thuis en drie dagen op kantoor.' },
  { t: 'open', q: 'Wat vindt u ervan dat kinderen op de basisschool al Engels leren? Geef uw mening met minstens twee argumenten.', min: 55, model: 'Ik vind het een goed idee dat kinderen op de basisschool al Engels leren. Jonge kinderen nemen een taal veel sneller op dan volwassenen. Bovendien hebben zij later op de middelbare school en op hun werk profijt van die basis. Sommige ouders vinden het te vroeg, maar één uur per week gaat niet ten koste van rekenen of taal.' },
  { t: 'open', q: 'Vergelijk het openbaar vervoer in Nederland met het vervoer in uw land van herkomst.', min: 60, model: 'Het openbaar vervoer in Nederland is goed geregeld. De treinen rijden vaak en meestal op tijd, en met één kaart kun je in bijna heel het land reizen. In mijn land van herkomst rijden er meer bussen en minibussen, maar er is geen vaste dienstregeling. Daar is reizen wel veel goedkoper. Alles bij elkaar vind ik het Nederlandse systeem betrouwbaarder, maar duur.' },
  { t: 'open', q: 'Beschrijf een sollicitatiegesprek dat u hebt gehad. Wat ging goed en wat ging minder goed?', min: 60, model: 'Vorig jaar had ik een sollicitatiegesprek bij een zorginstelling. Ik had mij goed voorbereid en kon rustig vertellen over mijn ervaring in de thuiszorg. Dat ging goed. Minder goed ging het toen ik een vraag over de cao niet begreep; ik durfde toen niet om uitleg te vragen. Achteraf heb ik geleerd dat het juist verstandig is om iets nog een keer te laten uitleggen.' },
  { t: 'open', q: 'Moet iedereen die in Nederland komt wonen verplicht Nederlands leren? Geef uw mening met argumenten.', min: 60, model: 'Ik vind dat iedereen die hier komt wonen Nederlands moet leren. Zonder taal is het bijna onmogelijk om werk te vinden of een brief van de gemeente te begrijpen. Bovendien maak je zo veel sneller contact met buren en collega\'s. Wel vind ik dat de overheid goede en betaalbare cursussen moet aanbieden, want anders is de verplichting oneerlijk voor mensen met weinig geld.' },
  { t: 'open', q: 'Vergelijk wonen in de stad met wonen in een dorp. Wat heeft uw voorkeur en waarom?', min: 60, model: 'In de stad is alles dichtbij: winkels, werk en het station. Er is veel te doen en je kunt overal met de fiets komen. Een dorp is rustiger en de huizen zijn er groter en goedkoper. Daar kennen de mensen elkaar ook beter. Zelf woon ik liever in de stad, omdat ik geen auto heb en mijn werk in het centrum ligt.' },
  { t: 'open', q: 'Beschrijf een keer dat u een probleem had met een organisatie of instantie en hoe u dat hebt opgelost.', min: 60, model: 'Twee jaar geleden kreeg ik een rekening van mijn energieleverancier van bijna duizend euro. Ik wist zeker dat dat niet klopte, want mijn meterstand was veel lager. Eerst heb ik gebeld, maar dat hielp niet. Daarna heb ik een brief geschreven met foto\'s van de meter. Uiteindelijk werd de rekening aangepast en kreeg ik geld terug. Ik heb geleerd dat je alles beter schriftelijk kunt regelen.' },
  { t: 'open', q: 'Wat vindt u van het gebruik van sociale media door jongeren? Geef uw mening met redenen.', min: 55, model: 'Sociale media hebben voor jongeren goede en slechte kanten. Ze houden makkelijk contact met vrienden en vinden er informatie voor school. Aan de andere kant zitten veel jongeren uren per dag op hun telefoon, waardoor ze slecht slapen en minder bewegen. Ik vind daarom dat ouders afspraken moeten maken over schermtijd, in plaats van alles te verbieden.' },
  { t: 'open', q: 'Vergelijk werken in loondienst met werken als zelfstandige. Noem voor- en nadelen.', min: 60, model: 'Wie in loondienst werkt, heeft elke maand een vast salaris en is verzekerd bij ziekte. Ook krijg je vakantiedagen en soms een cursus van je werkgever. Een zelfstandige verdient soms meer en kan zelf bepalen wanneer hij werkt. Maar hij moet zijn eigen verzekering en pensioen regelen en heeft geen inkomen als er weinig opdrachten zijn. Voor mij weegt zekerheid het zwaarst.' },
  { t: 'open', q: 'Beschrijf hoe uw leven veranderd is sinds u in Nederland woont.', min: 60, model: 'Sinds ik in Nederland woon, is er veel veranderd. In het begin was alles moeilijk: de taal, het weer en de directe manier van praten. Inmiddels werk ik in een fietsenwinkel en spreek ik elke dag Nederlands met klanten. Ik ga nu overal met de fiets naartoe, ook als het regent. Wat ik het meest mis, is mijn familie en het eten van thuis.' },
];

export const SPREKEN = [
  // ---------- korte taken, 20 seconden (30) ----------
  { t: 'sp', l: 'U bent te laat voor uw afspraak bij de gemeente. De medewerker aan de balie kijkt u vragend aan. Wat zegt u?', q: 'Reageer op de situatie.', kw: [['sorry'], ['excuses'], ['te', 'laat']], model: 'Sorry dat ik te laat ben, ik stond onverwacht in de file. Kan ik nog geholpen worden?', sec: 20 },
  { t: 'sp', l: 'U bent ziek en kunt vandaag niet werken. U belt uw leidinggevende. Wat zegt u?', q: 'Meld u ziek.', kw: [['ziek'], ['koorts'], ['griep'], ['niet', 'werken']], model: 'Goedemorgen, met Amina. Ik ben ziek geworden en heb koorts, dus ik kan vandaag helaas niet komen werken.', sec: 20 },
  { t: 'sp', l: 'U hebt gisteren kaas gekocht, maar die blijkt bedorven te zijn. U staat weer in de winkel. Wat zegt u?', q: 'Leg het probleem uit.', kw: [['bedorven'], ['over', 'datum'], ['ruilen'], ['geld', 'terug']], model: 'Ik heb deze kaas gisteren bij u gekocht, maar hij is bedorven. Kan ik hem ruilen of krijg ik mijn geld terug?', sec: 20 },
  { t: 'sp', l: 'Een collega vraagt of u zaterdag zijn dienst kunt overnemen, maar dat lukt u niet. Wat zegt u?', q: 'Reageer op de vraag.', kw: [['helaas'], ['sorry'], ['lukt', 'niet'], ['kan', 'niet']], model: 'Sorry, dat lukt me helaas niet. Zaterdag ga ik met mijn kinderen naar mijn ouders. Volgende week kan ik wel.', sec: 20 },
  { t: 'sp', l: 'Uw buurvrouw vraagt of u tijdens haar vakantie haar planten water wilt geven. Wat zegt u?', q: 'Reageer op het verzoek.', kw: [['natuurlijk'], ['prima'], ['graag'], ['sleutel']], model: 'Ja hoor, dat doe ik graag. Geeft u mij de sleutel maar even en zegt u erbij hoe vaak ik water moet geven.', sec: 20 },
  { t: 'sp', l: 'U wilt een afspraak maken bij de tandarts. De assistente neemt de telefoon op. Wat zegt u?', q: 'Maak een afspraak.', kw: [['afspraak'], ['tandarts'], ['controle'], ['maken']], model: 'Goedemiddag, met Yusuf Aydin. Ik zou graag een afspraak maken voor een controle, het liefst laat in de middag.', sec: 20 },
  { t: 'sp', l: 'U staat bij het loket van de gemeente. De medewerker vraagt waarvoor u komt. U wilt uw paspoort verlengen. Wat zegt u?', q: 'Zeg waarvoor u komt.', kw: [['paspoort'], ['verlengen'], ['aanvragen'], ['verloopt']], model: 'Ik kom mijn paspoort verlengen. Het verloopt volgende maand en ik heb mijn oude paspoort en een pasfoto meegenomen.', sec: 20 },
  { t: 'sp', l: 'U hebt uw trein gemist en komt een half uur te laat op uw werk. U belt uw collega. Wat zegt u?', q: 'Leg uit wat er is.', kw: [['trein'], ['gemist'], ['vertraging'], ['te', 'laat']], model: 'Hoi Ellen, ik heb mijn trein gemist en ben ongeveer een half uur later. Kun jij de kassa zolang overnemen?', sec: 20 },
  { t: 'sp', l: 'Een collega bedankt u, omdat u hem geholpen hebt met een lastige klant. Wat zegt u?', q: 'Reageer op uw collega.', kw: [['graag', 'gedaan'], ['geen', 'probleem'], ['altijd'], ['niets']], model: 'Graag gedaan, geen probleem. Je helpt mij ook altijd als het druk is, dus vraag het gerust nog een keer.', sec: 20 },
  { t: 'sp', l: 'U zit bij de kapper. De kapper vraagt hoe u uw haar wilt hebben. Wat zegt u?', q: 'Zeg wat u wilt.', kw: [['kort'], ['knippen'], ['centimeter'], ['model']], model: 'Graag een paar centimeter eraf, maar niet te kort. Het model mag hetzelfde blijven, alleen wat netter.', sec: 20 },
  { t: 'sp', l: 'Uw zoon is ziek en kan niet naar school. U belt de school. Wat zegt u?', q: 'Meld uw kind ziek.', kw: [['ziek'], ['koorts'], ['niet', 'komen'], ['thuis']], model: 'Goedemorgen, u spreekt met de moeder van Adem uit groep 6. Hij is ziek en heeft koorts, dus hij komt vandaag niet.', sec: 20 },
  { t: 'sp', l: 'U wilt een pakket terugsturen. U belt de klantenservice van de webwinkel. Wat zegt u?', q: 'Leg uit wat u wilt.', kw: [['terugsturen'], ['retour'], ['pakket'], ['bestelling']], model: 'Goedemiddag, ik wil graag een bestelling retour sturen. De schoenen zijn te klein. Hoe kan ik dat het beste doen?', sec: 20 },
  { t: 'sp', l: 'Uw bovenburen maken laat op de avond veel lawaai. U belt bij hen aan. Wat zegt u?', q: 'Spreek uw buren aan.', kw: [['lawaai'], ['geluid'], ['zachter'], ['slapen']], model: 'Sorry dat ik zo laat stoor, maar ik hoor bij mij alles. Zouden jullie de muziek wat zachter kunnen zetten? Ik moet morgen vroeg op.', sec: 20 },
  { t: 'sp', l: 'Een onbekende vraagt u op straat hoe hij naar het centraal station moet lopen. Wat zegt u?', q: 'Leg de weg uit.', kw: [['rechtdoor'], ['links'], ['rechts'], ['station']], model: 'U loopt hier rechtdoor tot aan het grote kruispunt en gaat daar linksaf. Dan ziet u het station al liggen, ongeveer tien minuten lopen.', sec: 20 },
  { t: 'sp', l: 'De printer op kantoor doet het niet meer. U belt de helpdesk. Wat zegt u?', q: 'Meld de storing.', kw: [['printer'], ['kapot'], ['werkt', 'niet'], ['storing']], model: 'Goedemorgen, met Nora van de afdeling inkoop. De printer op de tweede verdieping doet het niet meer; hij geeft steeds een foutmelding.', sec: 20 },
  { t: 'sp', l: 'Uw leidinggevende vraagt of u volgende week een extra dag kunt werken. Wat zegt u?', q: 'Reageer op de vraag.', kw: [['prima'], ['geen', 'probleem'], ['helaas'], ['woensdag']], model: 'Dat is geen probleem, woensdag kan ik wel extra werken. Alleen moet ik dan om vier uur weg voor mijn dochter.', sec: 20 },
  { t: 'sp', l: 'U bent bij de huisarts. De arts vraagt welke klachten u hebt. Wat zegt u?', q: 'Vertel uw klachten.', kw: [['pijn'], ['hoofdpijn'], ['koorts'], ['hoest']], model: 'Ik heb al een week last van hoofdpijn en ik ben erg moe. Vooral \'s middags wordt de pijn erger.', sec: 20 },
  { t: 'sp', l: 'U wilt vrijdag vrij nemen voor een bruiloft. U spreekt uw leidinggevende aan. Wat zegt u?', q: 'Vraag een dag vrij.', kw: [['vrij'], ['verlof'], ['bruiloft'], ['vrijdag']], model: 'Zou ik vrijdag vrij mogen nemen? Mijn nicht gaat dan trouwen. Ik kan die uren in de week erna inhalen.', sec: 20 },
  { t: 'sp', l: 'U hebt een rekening gekregen voor iets wat u niet besteld hebt. U belt het bedrijf. Wat zegt u?', q: 'Leg het probleem uit.', kw: [['rekening'], ['klopt', 'niet'], ['niet', 'besteld'], ['factuur']], model: 'Goedemiddag, ik heb een rekening ontvangen die volgens mij niet klopt. Ik heb dit abonnement nooit besteld. Kunt u dat nakijken?', sec: 20 },
  { t: 'sp', l: 'Een collega vraagt maandagochtend hoe uw weekend was. Wat zegt u?', q: 'Vertel kort over uw weekend.', kw: [['weekend'], ['leuk'], ['gezellig'], ['rustig']], model: 'Heel gezellig, dank je. Zaterdag ben ik met de kinderen naar het park geweest en zondag hebben we lekker rustig thuis gezeten.', sec: 20 },
  { t: 'sp', l: 'Het is uw eerste dag op een nieuwe afdeling. U stelt zich voor aan het team. Wat zegt u?', q: 'Stel uzelf voor.', kw: [['heet'], ['naam'], ['nieuw'], ['werk']], model: 'Hallo allemaal, ik ben Karim Belhaj en ik kom het team versterken op de administratie. Ik heb hiervoor vijf jaar bij een verzekeraar gewerkt.', sec: 20 },
  { t: 'sp', l: 'Een verkoper in een kledingwinkel vraagt of u geholpen wordt. U zoekt een winterjas. Wat zegt u?', q: 'Zeg wat u zoekt.', kw: [['jas'], ['zoek'], ['maat'], ['winterjas']], model: 'Ik zoek een warme winterjas in maat 52, het liefst donkerblauw. Hebt u die op voorraad?', sec: 20 },
  { t: 'sp', l: 'U kunt niet op uw afspraak bij de gemeente komen. U belt om die te verzetten. Wat zegt u?', q: 'Verzet de afspraak.', kw: [['verzetten'], ['verplaatsen'], ['afspraak'], ['andere', 'dag']], model: 'Goedemiddag, ik heb donderdag om tien uur een afspraak, maar die kan ik niet halen. Kan ik hem verzetten naar een andere dag?', sec: 20 },
  { t: 'sp', l: 'Uw fiets is gestolen. U staat bij de politie om aangifte te doen. Wat zegt u?', q: 'Doe aangifte.', kw: [['fiets'], ['gestolen'], ['aangifte'], ['weg']], model: 'Ik kom aangifte doen, want mijn fiets is gestolen. Hij stond gisteravond op slot bij het station en vanmorgen was hij weg.', sec: 20 },
  { t: 'sp', l: 'Een vriend nodigt u uit voor zijn verjaardag, maar u moet die avond werken. Wat zegt u?', q: 'Reageer op de uitnodiging.', kw: [['helaas'], ['werken'], ['dienst'], ['kan', 'niet']], model: 'Wat leuk dat je me vraagt, maar ik moet die avond helaas werken. Ik heb avonddienst. Kunnen we het weekend erna iets afspreken?', sec: 20 },
  { t: 'sp', l: 'U bent in de bibliotheek en wilt lid worden. Wat vraagt u aan de medewerker?', q: 'Stel uw vraag.', kw: [['lid'], ['abonnement'], ['inschrijven'], ['kost']], model: 'Goedemiddag, ik zou graag lid willen worden. Kunt u mij vertellen wat een abonnement per jaar kost en wat ik daarvoor mee moet nemen?', sec: 20 },
  { t: 'sp', l: 'Uw verhuurder belt en zegt dat de huur volgend jaar omhooggaat. Wat zegt u?', q: 'Reageer op het nieuws.', kw: [['huur'], ['hoog'], ['waarom'], ['brief']], model: 'Dat vind ik behoorlijk veel. Kunt u mij uitleggen waarom de huur zoveel omhooggaat en dat ook schriftelijk bevestigen?', sec: 20 },
  { t: 'sp', l: 'U staat bij de apotheek. Uw medicijn is niet op voorraad. Wat zegt u?', q: 'Reageer op de apotheker.', kw: [['medicijn'], ['wanneer'], ['ander'], ['apotheek']], model: 'Wanneer is het medicijn weer binnen? Ik heb het morgen echt nodig. Is er anders een andere apotheek die het wel heeft?', sec: 20 },
  { t: 'sp', l: 'Uw collega heeft een fout gemaakt in het rooster: u staat twee keer op zondag ingeroosterd. Wat zegt u?', q: 'Meld de fout.', kw: [['rooster'], ['fout'], ['klopt', 'niet'], ['zondag']], model: 'Volgens mij klopt het rooster niet. Ik sta twee zondagen achter elkaar ingepland, terwijl we hadden afgesproken om en om te werken.', sec: 20 },
  { t: 'sp', l: 'U komt te laat op de ouderavond van de school van uw dochter. De docent doet de deur open. Wat zegt u?', q: 'Reageer op de situatie.', kw: [['sorry'], ['te', 'laat'], ['excuses'], ['file']], model: 'Mijn excuses dat ik te laat ben, ik kwam net van mijn werk en stond in de file. Kunnen we het gesprek toch nog voeren?', sec: 20 },

  // ---------- middellange taken, 30 seconden (30) ----------
  { t: 'sp', l: 'Vertel over uw werk. Wat doet u precies en wat vindt u er leuk aan?', q: 'Vertel over uw werk.', kw: [['werk'], ['baan'], ['collega'], ['leuk']], model: 'Ik werk als verzorgende in een verpleeghuis. Ik help bewoners met wassen, aankleden en eten. Het leukste vind ik het contact met de bewoners en met mijn collega\'s; geen dag is hetzelfde.', sec: 30 },
  { t: 'sp', l: 'Waarom leert u Nederlands? Leg uit wat u ermee wilt bereiken.', q: 'Leg het uit.', kw: [['nederlands'], ['leren'], ['werk'], ['praten']], model: 'Ik leer Nederlands vooral voor mijn werk. Ik wil met klanten kunnen praten zonder dat een collega moet vertalen. Daarnaast wil ik brieven van de gemeente zelf kunnen begrijpen en later een opleiding volgen.', sec: 30 },
  { t: 'sp', l: 'Wat vindt u van thuiswerken? Geef uw mening en noem een reden.', q: 'Geef uw mening.', kw: [['thuiswerken'], ['omdat'], ['kantoor'], ['vind']], model: 'Ik vind thuiswerken prettig, omdat ik dan geen tijd verlies in het verkeer en rustiger kan werken. Toch wil ik niet alle dagen thuis zijn, want het contact met collega\'s mis ik dan te veel.', sec: 30 },
  { t: 'sp', l: 'Uw werkgever stelt voor dat iedereen voortaan een half uur eerder begint. Wat vindt u van dat voorstel?', q: 'Reageer op het voorstel.', kw: [['eerder'], ['vroeg'], ['omdat'], ['kinderen']], model: 'Voor mij is een half uur eerder beginnen lastig, omdat ik dan mijn kinderen niet naar school kan brengen. Ik zou het beter vinden als mensen zelf mogen kiezen tussen half acht en half negen.', sec: 30 },
  { t: 'sp', l: 'Vertel over een cursus of opleiding die u hebt gevolgd. Wat hebt u geleerd?', q: 'Vertel erover.', kw: [['cursus'], ['opleiding'], ['geleerd'], ['diploma']], model: 'Vorig jaar heb ik een cursus heftruck gevolgd bij mijn werkgever. De cursus duurde drie dagen en daarna heb ik examen gedaan. Ik heb vooral geleerd hoe je veilig laadt en lost, en ik heb nu mijn certificaat.', sec: 30 },
  { t: 'sp', l: 'Beschrijf uw woning en de buurt waarin u woont.', q: 'Beschrijf uw woning.', kw: [['woon'], ['huis'], ['buurt'], ['kamers']], model: 'Ik woon in een appartement op de derde verdieping met twee slaapkamers en een klein balkon. De buurt is rustig en groen. De supermarkt en de school van mijn dochter zijn op loopafstand, dat vind ik heel prettig.', sec: 30 },
  { t: 'sp', l: 'Wat is voor u het grootste verschil tussen Nederland en uw land van herkomst?', q: 'Leg het verschil uit.', kw: [['verschil'], ['nederland'], ['anders'], ['land']], model: 'Het grootste verschil is dat mensen hier alles van tevoren plannen. In mijn land ga je gewoon langs bij familie, hier maak je eerst een afspraak. Ook zijn Nederlanders veel directer; in het begin schrok ik daarvan, maar nu vind ik het duidelijk.', sec: 30 },
  { t: 'sp', l: 'De gemeente wil in uw straat parkeerplaatsen weghalen om meer groen aan te leggen. Wat vindt u daarvan?', q: 'Geef uw mening.', kw: [['parkeer'], ['groen'], ['auto'], ['vind']], model: 'Meer groen in de straat vind ik een goed plan, want het is er in de zomer erg warm. Maar als er parkeerplaatsen verdwijnen, moeten bewoners wel ergens anders kunnen parkeren, anders wordt het alleen maar drukker.', sec: 30 },
  { t: 'sp', l: 'Vertel over een keer dat u iets moest regelen bij de gemeente. Hoe ging dat?', q: 'Vertel erover.', kw: [['gemeente'], ['afspraak'], ['formulier'], ['aanvragen']], model: 'Toen ik verhuisde, moest ik mijn adres doorgeven bij de gemeente. Ik heb online een afspraak gemaakt en mijn identiteitskaart meegenomen. Aan de balie ging het snel, maar het invullen van het formulier vond ik lastig door de moeilijke woorden.', sec: 30 },
  { t: 'sp', l: 'Wat doet u om gezond te blijven? Leg uit.', q: 'Leg het uit.', kw: [['gezond'], ['sport'], ['eten'], ['wandel']], model: 'Ik probeer elke dag te bewegen: ik ga met de fiets naar mijn werk en in het weekend wandel ik een uur. Verder let ik op mijn eten en kook ik zelf, zodat ik weet wat erin zit.', sec: 30 },
  { t: 'sp', l: 'Uw collega\'s willen samen een cadeau kopen voor een jarige collega en vragen of u meedoet. Wat zegt u?', q: 'Reageer op het voorstel.', kw: [['cadeau'], ['meedoen'], ['goed', 'idee'], ['euro']], model: 'Goed idee, ik doe graag mee. Ik leg tien euro in. Zullen we een cadeaubon voor de tuincentrum kopen? Ik weet dat zij veel met planten bezig is.', sec: 30 },
  { t: 'sp', l: 'Vertel over een reis of vakantie die u hebt gemaakt.', q: 'Vertel erover.', kw: [['vakantie'], ['reis'], ['week'], ['bezocht']], model: 'Vorige zomer ben ik twee weken naar mijn familie geweest. We hebben veel oude vrienden bezocht en zijn een paar dagen naar zee gegaan. Het was warm en druk, maar vooral gezellig om iedereen weer te zien.', sec: 30 },
  { t: 'sp', l: 'Wat vindt u belangrijk in een baan? Leg uit waarom.', q: 'Leg het uit.', kw: [['belangrijk'], ['salaris'], ['collega'], ['omdat']], model: 'Voor mij zijn goede collega\'s het belangrijkst, omdat je acht uur per dag samen bent. Daarnaast let ik op vaste werktijden, want ik moet mijn werk kunnen combineren met mijn gezin. Salaris is belangrijk, maar niet het enige.', sec: 30 },
  { t: 'sp', l: 'Mogen kinderen hun mobiele telefoon meenemen naar school? Wat vindt u daarvan?', q: 'Geef uw mening.', kw: [['telefoon'], ['school'], ['kinderen'], ['vind']], model: 'Ik vind dat kinderen hun telefoon wel mee mogen nemen, maar dat die tijdens de les in een kluisje moet. Zo kunnen ze na school bellen, terwijl ze in de klas niet worden afgeleid.', sec: 30 },
  { t: 'sp', l: 'Vertel over een probleem in uw buurt en zeg wat er volgens u moet gebeuren.', q: 'Vertel erover.', kw: [['buurt'], ['probleem'], ['gemeente'], ['moet']], model: 'In onze straat rijden auto\'s veel te hard, terwijl er veel kinderen spelen. Ik vind dat de gemeente drempels moet aanleggen en betere verlichting moet plaatsen. De buurtvereniging heeft daar vorige maand een brief over geschreven.', sec: 30 },
  { t: 'sp', l: 'Uw leidinggevende wil dat u een verplichte cursus volgt op zaterdag. Wat zegt u?', q: 'Reageer op het voorstel.', kw: [['zaterdag'], ['cursus'], ['familie'], ['liever']], model: 'Ik wil de cursus graag volgen, maar zaterdag is voor mij lastig, want dan zorg ik voor mijn kinderen. Kan de cursus ook doordeweeks, of kan ik die uren dan compenseren?', sec: 30 },
  { t: 'sp', l: 'Beschrijf hoe een gewone werkdag bij u eruitziet.', q: 'Beschrijf uw dag.', kw: [['ochtend'], ['werk'], ['uur'], ['daarna']], model: 'Ik sta om zes uur op en ga met de fiets naar mijn werk. Om zeven uur begin ik in het magazijn met het klaarzetten van de bestellingen. Rond twaalf uur eet ik met collega\'s, en daarna rijd ik nog twee routes.', sec: 30 },
  { t: 'sp', l: 'Wat vindt u van het openbaar vervoer in Nederland? Geef een voorbeeld.', q: 'Geef uw mening.', kw: [['trein'], ['bus'], ['duur'], ['op', 'tijd']], model: 'Over het algemeen ben ik tevreden: de trein rijdt vaak en meestal op tijd. Wel vind ik het duur. Vorige week betaalde ik ruim twintig euro voor een rit naar Groningen, terwijl de trein ook nog vertraging had.', sec: 30 },
  { t: 'sp', l: 'Vertel over een keer dat u iemand geholpen hebt.', q: 'Vertel erover.', kw: [['geholpen'], ['hulp'], ['buurvrouw'], ['collega']], model: 'Mijn buurvrouw is 82 en kon haar formulier voor huurtoeslag niet invullen. Ik ben bij haar gaan zitten en heb alles samen met haar doorgenomen. Ze was erg blij, want ze had er wekenlang tegenop gezien.', sec: 30 },
  { t: 'sp', l: 'Sommige mensen vinden dat iedereen vrijwilligerswerk zou moeten doen. Wat vindt u daarvan?', q: 'Geef uw mening.', kw: [['vrijwilligerswerk'], ['verplicht'], ['tijd'], ['vind']], model: 'Vrijwilligerswerk is heel waardevol, maar ik vind niet dat het verplicht moet zijn. Veel mensen werken al fulltime en zorgen daarnaast voor familie. Vrijwillig helpen werkt alleen als je het echt zelf wilt.', sec: 30 },
  { t: 'sp', l: 'Wilt u in Nederland blijven wonen? Leg uit waarom wel of niet.', q: 'Leg het uit.', kw: [['blijven'], ['nederland'], ['omdat'], ['kinderen']], model: 'Ik wil hier blijven wonen, vooral omdat mijn kinderen hier naar school gaan en goede kansen krijgen. Ook heb ik vast werk gevonden. Wat ik mis, is mijn familie, dus we gaan elk jaar een paar weken terug.', sec: 30 },
  { t: 'sp', l: 'Wat doet u in uw vrije tijd en waarom?', q: 'Vertel erover.', kw: [['vrije', 'tijd'], ['sport'], ['lezen'], ['ontspan']], model: 'In mijn vrije tijd voetbal ik op woensdagavond en fiets ik in het weekend met mijn man. Daar ontspan ik van na een drukke werkweek. Verder lees ik graag, want dat helpt ook met mijn Nederlands.', sec: 30 },
  { t: 'sp', l: 'Uw buren willen een buurtfeest organiseren en vragen uw hulp. Wat zegt u?', q: 'Reageer op het verzoek.', kw: [['buurtfeest'], ['helpen'], ['leuk'], ['organiseren']], model: 'Wat een leuk idee, daar help ik graag aan mee. Ik kan salades maken en tafels regelen. Alleen op zaterdagochtend werk ik, dus vanaf twee uur ben ik beschikbaar.', sec: 30 },
  { t: 'sp', l: 'Wat vindt u van de zorg in Nederland? Geef een voorbeeld uit uw eigen ervaring.', q: 'Geef uw mening.', kw: [['huisarts'], ['zorg'], ['ziekenhuis'], ['wachten']], model: 'De zorg is hier goed geregeld, maar je moet vaak lang wachten. Toen ik last had van mijn knie, kreeg ik van de huisarts eerst het advies om af te wachten. Pas na twee maanden mocht ik naar het ziekenhuis.', sec: 30 },
  { t: 'sp', l: 'Vertel over een sollicitatiegesprek dat u hebt gehad. Hoe ging het?', q: 'Vertel erover.', kw: [['sollicitatie'], ['gesprek'], ['vragen'], ['baan']], model: 'Ik had een gesprek bij een schoonmaakbedrijf. Ze vroegen naar mijn ervaring en naar hoe ik omga met drukte. Ik was zenuwachtig, maar ik heb rustig geantwoord. Een week later kreeg ik de baan.', sec: 30 },
  { t: 'sp', l: 'Moeten werknemers verplicht naar kantoor komen? Wat vindt u?', q: 'Geef uw mening.', kw: [['kantoor'], ['thuis'], ['omdat'], ['vind']], model: 'Ik vind een verplichting niet nodig. Wie thuis goed werkt, moet dat kunnen blijven doen. Wel is het handig als iedereen één of twee vaste dagen op kantoor is, omdat overleg dan veel sneller gaat.', sec: 30 },
  { t: 'sp', l: 'Vertel over iemand die belangrijk voor u is en leg uit waarom.', q: 'Vertel erover.', kw: [['belangrijk'], ['moeder'], ['vriend'], ['omdat']], model: 'De belangrijkste persoon voor mij is mijn moeder. Zij heeft ons alleen opgevoed en altijd gezorgd dat wij konden studeren. Ik bel haar elke zondag, omdat ik haar advies nog steeds heel serieus neem.', sec: 30 },
  { t: 'sp', l: 'Leg uit hoe u in het dagelijks leven geld bespaart.', q: 'Leg het uit.', kw: [['besparen'], ['geld'], ['aanbieding'], ['fiets']], model: 'Ik let goed op de aanbiedingen en maak altijd een boodschappenlijst, zodat ik niet te veel koop. Verder ga ik met de fiets naar mijn werk in plaats van met de auto. Zo bespaar ik elke maand een flink bedrag.', sec: 30 },
  { t: 'sp', l: 'De school van uw kind wil de lestijden veranderen: de school begint een half uur later. Wat vindt u daarvan?', q: 'Geef uw mening.', kw: [['lestijden'], ['school'], ['werk'], ['vind']], model: 'Voor mij is dat lastig, omdat ik zelf om acht uur moet beginnen met werken. Als de school later begint, moet er opvang zijn vanaf half acht. Dan vind ik het een prima plan.', sec: 30 },
  { t: 'sp', l: 'Vertel over iets uit het nieuws dat u de laatste tijd is opgevallen.', q: 'Vertel erover.', kw: [['nieuws'], ['gelezen'], ['gehoord'], ['vind']], model: 'Ik heb gelezen dat de huren in veel steden weer stijgen. Dat valt mij op, want in onze buurt zoeken jonge mensen al maanden een woning. Ik vind dat er veel sneller gebouwd moet worden.', sec: 30 },
];
